### ISSUE TITLE
Refactor SignallingWebServer to be consumable as an extensible libarary

### ISSUE THREAD

**Issue by mentalnote** [EpicGames/PixelStreamingInfrastructure-archived-2024#10]
Similar to https://github.com/EpicGames/PixelStreamingInfrastructure/issues/9, we want to update the SignallingWebServer scripts so they can be interfaced with as a library.

This will more easily allow users to simply integrate the functionality they need from the library into their own infrastructure, along with the benefits described in the referred to issue above.

Names for this library up for discussion.

**Comment by jimcccc** [comment]
Ok

**Comment by DenisTensorWorks** [comment]
This issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/1
