### ISSUE TITLE
Refactor SFU to be consumable as an extensible libarary

### ISSUE THREAD

**Issue by mentalnote** [EpicGames/PixelStreamingInfrastructure-archived-2024#11]
Similar to https://github.com/EpicGames/PixelStreamingInfrastructure/issues/9, we want to update the SFU scripts so they can be interfaced with as a library.

This will more easily allow users to simply integrate the functionality they need from the library into their own infrastructure, along with the benefits described in the referred to issue above.

We should expose this as `lib-pssfu`

**Comment by jimcccc** [comment]
Ok

**Comment by DenisTensorWorks** [comment]
This issue has been migrated to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/2
