### ISSUE TITLE
Does pixel streaming support Client/Server mode?

### ISSUE THREAD

**Issue by jiuhaizhang** [EpicGames/PixelStreamingInfrastructure-archived-2024#111]
I have machines that have public IP and I deploy UE aplication in these servers, can client connect to server directly without TURN/STUN? It can reduce latency

**Comment by jimcccc** [comment]
Ok

**Comment by jimcccc** [comment]
Ok

**Comment by lukehb** [comment]
The answer is "yes" (with caveats).

WebRTC does support direct connections if machines are on the same network.

However, often machines are not on the same network (i.e. they are running over the internet). In such cases, at the very least, STUN must be used. 

I will note, **STUN does not introduce latency**.

However, to directly answer your question, "Does pixel streaming support Client/Server mode?"

No.
