### ISSUE TITLE
Locked mouse scaling seems too sensitive

### ISSUE THREAD

**Issue by lukehb** [EpicGames/PixelStreamingInfrastructure-archived-2024#112]
Steps to reproduce:

- Enable pointer locked mode using settings, Control Scheme: Locked
- Focus the UE application, do some small circles with the mouse to move the camera
- Focus the Pixel Streaming browser tab, do the same motion with the mouse
- Note the sensitivity seems much higher.

This does not appear to reproduce when using "hovering mouse mode".

CC @Belchy06 to review.

**Comment by lukehb** [comment]
Seems we may have a lead with mouse getting registered multiple times perhaps?

**Comment by WOOB4T** [comment]
@EpicGames/developers this software is incredible.

**Comment by Belchy06** [comment]
Issue was resolved as part of https://github.com/EpicGames/PixelStreamingInfrastructure/commit/95f2bef3349b6b715e3261a259afe6e0bed53c9d
