### ISSUE TITLE
Links broken in documentation

### ISSUE THREAD

**Issue by tdsticks** [EpicGames/PixelStreamingInfrastructure-archived-2024#121]
Hi, I'm seeing broken links throughout your documentation. Can you please fix the links?

https://github.com/EpicGames/PixelStreamingInfrastructure/tree/master/Frontend

1. https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/Frontend/Docs%5CCustomizing%20the%20Player%20Webpage.md
2. https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/Frontend/Docs%5CHTML%20Page%20Requirements.md
3. https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/Frontend/Docs%5CHTML%20Page%20Requirements.md
4. https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/Frontend/Docs/Resources%5CImages%5Cpixelstreaming-add-component.jpg

There are more, I don't have time to post all of the broken links.

**Comment by Belchy06** [comment]
Should be fixed as of: https://github.com/EpicGames/PixelStreamingInfrastructure/commit/eb61688868600df4799133236e7058557ca26c05
