### ISSUE TITLE
Container images/docker files SFU and Matchmaker

### ISSUE THREAD

**Issue by mentalnote** [EpicGames/PixelStreamingInfrastructure-archived-2024#13]
We currently provide scripts which will install all the required dependencies and run each of the SignallingWebServer, SFU, or Matchmaker. This works pretty well but still involves machinery with the potential to fail in not accounted for environments.

We can sidestep these difficulties by additionally providing a mechanism to build these individual applications as a standalone executable using a technology such as https://github.com/nexe/nexe

**Comment by jimcccc** [comment]
Ok

**Comment by jimcccc** [comment]
Ok

**Comment by lukehb** [comment]
I think I will change this be container images - we already have this Signalling, so just SFU and matchmaker missing.

**Comment by DenisTensorWorks** [comment]
This issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/4
