### ISSUE TITLE
NPM package releases

### ISSUE THREAD

**Issue by mentalnote** [EpicGames/PixelStreamingInfrastructure-archived-2024#14]
First we need to complete the following tasks:

- [x] #9 
- [x] #10 
- [x] #11 
- [x] #12

Once we have done this, we can further improve the user experience in using `PixelStreamingInfrastructure` by synthesising it's libraries into a single or multiple semantically versioned npm packages, generating these automatically as new changes make their way into this repository.

**Comment by sheepsteak** [comment]
Is there any chance that the various packages could be written in TypeScript or at least have types shipped with them?

Also, is there any timeframe for when this will all happen? Is it to coincide with a UE5.1 release?

**Comment by mentalnote** [comment]
Sorry for the delay in response to this. At the moment, I would expect this to be done sometime after UE5.1 release.

**Comment by lukehb** [comment]
There are now some unofficial NPM packages up for the frontend library here: https://www.npmjs.com/settings/epicgames-ps/packages

Official packages to come through Github packages in the future.

**Comment by lukehb** [comment]
@sheepsteak 

> Is there any chance that the various packages could be written in TypeScript or at least have types shipped with them?

Yes, we have just rewritten the entire `Frontend/` in TypeScript and the plan is to move signalling server, matchmaker, and SFU to TypeScript too! The next one to tackle will be the signalling server - that will be undertaken as part of 5.3 I expect.

**Comment by jimcccc** [comment]
Ok

**Comment by DenisTensorWorks** [comment]
This issue has been move to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/5
