### ISSUE TITLE
could you help to send an invitation to join epic games

### ISSUE THREAD

**Issue by ppzzp** [EpicGames/PixelStreamingInfrastructure-archived-2024#157]
I connected github and epic games account, but no invitation received, could you please help, thanks~ @EpicTeamAdmin

**Comment by DenisTensorWorks** [comment]
Hi there,

You might have to contact the support team for this. Double-check that you are checking the correct email associated with the account and that the invitation email didn't go to spam. Check that you didn't miss any of the steps below:

https://www.epicgames.com/help/en-US/epic-accounts-c5719348850459/connect-accounts-c5719351300507/how-do-i-link-my-unreal-engine-account-with-my-github-account-a5720369784347

And if you are still experiencing the issue, use the _Contact Us_ form on the page above.
