### ISSUE TITLE
Connecting to Unreal 5.1 app with the 5.2 frontend crashes on connect

### ISSUE THREAD

**Issue by kass-kass** [EpicGames/PixelStreamingInfrastructure-archived-2024#160]
Using the npm package `lib-pixelstreamingfrontend-ue5.2` with the standard signalling server and an Unreal app (both UE 5.1), and connecting to WebSocket connection on localhost, clicking the "play" button on the frontend, the streamer app crashes with
```
LogPixelStreaming: Error: Failed to set remote description: Failed to set remote answer sdp: Called in wrong state: stable
LogWindows: Error: appError called: Assertion failed: IsInGameThread() || IsInSlateThread() || IsInAsyncLoadingThread() [File:D:\build\++UE5\Sync\Engine\Source\Runtime\Slate\Public\Framework\Application\SlateApplication.h] [Line: 255] 
```

According to the debugger it comes from `FPixelStreamingInputHandler::HandleOnMouseLeave`, which triggers `FSlateApplication::Get()`. 

I understand that the readme of PixelStreamingInfrastructure states
>⚠️ There are breaking changes between UE versions - so make sure you get the right version. ⚠️

so this might be expected, since it's UE5.2 frontend + UE5.1 application. However, the latest stable engine version available is 5.1, and the only currently available frontend package is `-5.2`, so this is the only combination I could get.

**Comment by Belchy06** [comment]
Hi @kass-kass,

Thanks for creating this issue!

I tried repro-ing today using UE5.1.1 and the library you mentioned above and was unfortunately unable to repro, using both browser send offer and application send offer.

Are you able to share with us (either through public repo or adding us as maintainers to a private repo) your implementation?

Cheers

**Comment by kass-kass** [comment]
@Belchy06 Will try to isolate the issue today  in an empty project and send some more details on what exactly triggers the crash.

**Comment by kass-kass** [comment]
@Belchy06, 

## Crash demonstration repository:
https://github.com/kass-kass/PixelStreamCrashDemo. The repo contains:
 - a bare-bones Unreal 5.1 project (PS plugin enabled, a single map created with a text moving up and down).
 - a bare-bones implementation of the PS infra (a ts/webpack project, with several lines of code in index.ts which create an `Application` object to display/manage it)

## Steps to reproduce:
1. Prepare webpage 
    1. Go to the TS project root folder and `npm install .`, then `npm run build`
    2. Open the generated `/dist/index.html` page
2. Prepare streamer
    1. Open project in Unreal Engine 5.1.1 editor
    2. Click "play in editor" button
    3. In the "pixel streaming tools" dropdown, click "stream level editor"
3. Connect
    1. In the webpage sidebar, put `ws://127.0.0.1` as endpoint
    2. Click the big play button

## Expected result
The stream starts

## Actual result
UE Editor application crashes

*Note: this is the quickest/simplest way to test, but it's also possible to package game, and run signalling server separately instead of using the toolbar in-editor. The result is the same.*

**Comment by lukehb** [comment]
@Belchy06 or @MWillWallT to attempt a repro from above.

**Comment by kass-kass** [comment]
Hi! Wanted to check if there was any luck reproducing this issue? Let me know if there is any more info I can provide. Thank you.

**Comment by kass-kass** [comment]
@Belchy06 @lukehb Thank you for making the changes to fix this! I guess it's safe to close the issue?

Also, had a question about this fix. I read the fix comments, but didn't fully understand, as I'm not so familiar with details of WebRTC protocol. Just to clarify, with this fix, connecting locally is possible, but connecting in an Scalable Pixel Streaming context would not be possible? I.e.

✅ latest frontend ↔️ latest Cirrus ↔️ single UE5.1 streaming app
❎ latest frontend ↔️ SPS singalling ↔️ provisioned UE5.1 streaming app

**Comment by Belchy06** [comment]
@kass-kass using in an SPS context should work.

The issue came from our frontend doing some extra steps related to multi-streamer support.

For a bit of insight, if you're using SPS you'll be using the handshake process from 4.27 regardless of which version of UE you're actually using. In this process, the browser initiates the negotiation process by sending and offer. 

In UE5 and later, the browser sends a 'playerConnected' message to the application and then the application sends the offer.

For this reason, we try to maintain compatibility between both processes but in this case it had been broken.

Could I get you to give the latest frontend a go now? From my testing it fixed the problem but just want to double check. 

Cheers

**Comment by kass-kass** [comment]
@Belchy06 OK great, thanks for the explanation. Will check this out and close the issue if it works.

Since I am using the npm package, I guess your latest changes from this fix aren't published yet. Should I wait for the new npm release, or is there a way for me to easily use a local copy of the library?

**Comment by Belchy06** [comment]
Version 0.4.0 which contained this fix plus another was pushed to NPM yesterday, so you should be good to go.

**Comment by kass-kass** [comment]
Confirming that this works! Thank you again for fixing.
