### ISSUE TITLE
Gamepad indices clash with multiple peers

### ISSUE THREAD

**Issue by Belchy06** [EpicGames/PixelStreamingInfrastructure-archived-2024#164]
## Problem
When multiple peers are connected, each peer's controllers will increment from 0.

This means that if player 0 has 2 gamepads, they'll be assigned index 0 and index 1 and when player 1 connects with two gamepads of its own, they'll also be assigned index 0 and index 1 as illustrated below:

![Blank diagram (1)](https://user-images.githubusercontent.com/29305253/226218805-9c6c3e3e-98b1-4230-853c-69f94a4d62d1.png)

The clashing of these gamepads prevents use cases such as local multiplayer (co-op) experiences.

**Comment by lukehb** [comment]
Nice image, can we get this added to the PR?
