### ISSUE TITLE
Rename implementation/EpicGames to implementation/typescript

### ISSUE THREAD

**Issue by lukehb** [EpicGames/PixelStreamingInfrastructure-archived-2024#166]
Given we now have `implementation/react` we should rename our existing primary implementation from `implementation/EpicGames` to `implementation/typescript`.

This can then make way for `implementation/vue` or whatever else people prefer.

**Comment by Belchy06** [comment]
Note for dev who takes on this ticket:

There are a few places in the platform scripts that also assume `implementation/EpicGames`, these could just fixed with a simple find and replace to `implementation/typescript`

**Comment by lukehb** [comment]
Very good catch @Belchy06

**Comment by jimcccc** [comment]
Ok
