### ISSUE TITLE
MatchMaking is not able to manage session

### ISSUE THREAD

**Issue by gouravjoshicldcvr** [EpicGames/PixelStreamingInfrastructure-archived-2024#178]
HI

Same setup i deployed on AWS EKS and things working fine except below issue.
Issue: 
   Matchmaker is exposed on Load Balancer service.
   Signalling server is also expoed on Load balancer service which is having multiple pods in backend.
   
    When matchmaking is redirecting request to signalling server, request is being routed to random pods that are already being 
    used by some other user who is already playing game  which tends multiple user in same game.

    I think matchmaking is not able to manage session for this.
    Kindly help in the same.

**Comment by jimcccc** [comment]
Ok

**Comment by lukehb** [comment]
Have you got a terraform file or similar so we can reproduce your setup on AWS?
