### ISSUE TITLE
[BUG] - build-dev-all script broken in the ui-library package

### ISSUE THREAD

**Issue by dan-tw** [EpicGames/PixelStreamingInfrastructure-archived-2024#183]
**UE Version: **
N/A

**Frontend Version: **
All

**Problem component**
`ui-library` NPM script `build-dev-all`

**Description**
The NPM script `build-dev-all` appears to be broken in the `ui-library` package. This is causing the `build-dev-all` script to also fail in the implementation etc.

**Steps to Reproduce:**
1. Clone repo
2. `npm install` on the `library` and `ui-library` packages
3. cd into `Frontend/implementations/EpicGames`
4. run `npm install`
5. run `npm run build-dev-all`
6. Observe that it gets stuck 

** Note: It will also fail if you try to run `build-dev-all` from the `ui-library` package assuming you've run `npm install` everywhere .

**Expected behavior**
1. The build should complete without errors and not hang

**Comment by jimcccc** [comment]
Ok

**Comment by mcottontensor** [comment]
Running through these steps currently works fine. Possibly fixed with other work since.

**Comment by kroecks** [comment]
I encountered this issue and have fixed it locally.

I will submit a PR
