### ISSUE TITLE
Make the Websocket disconnect: 1006 error more informative for end users

### ISSUE THREAD

**Issue by sarahkrivan** [EpicGames/PixelStreamingInfrastructure-archived-2024#184]
**Component your feature request relates to**
- [x] Signalling server
- [x] Frontend library
- [x] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo

**Problem your feature solves? Please describe.**
Currently, all websocket disconnects are presented with the same "Websocket disconnected: 1006" error (see screenshot). This is a generic error, but not overly useful to assist with debugging whether UE disconnected or the browser disconnected.

**Describe the solution you'd like**
Ideally, rather than a catch all disconnect message, a user would be able to see which component has disconnected: e.g. UE disconnected, Signalling Server disconnected, Browser disconnected etc.

**Additional context**
![websocket-disconnected](https://user-images.githubusercontent.com/115057549/228996061-f9d3a378-7c17-4e93-9d7e-bad2cc27ae63.png)

**Comment by jimcccc** [comment]
Ok
