### ISSUE TITLE
[Segmentation fault] - Engine crash handling finished

### ISSUE THREAD

**Issue by alelav79** [EpicGames/PixelStreamingInfrastructure-archived-2024#186]
Hi,

./MYBUILD_427.sh -RenderOffScreen -PixelStreamingURL=ws://IPSERVER:8888

after starting the stream I get this error

............................

Failed to find symbol file, expected location:
"/home/ubuntu/PixelStreamingTest_PointCloud_01/LinuxNoEditor/MYBUILD_427/Binaries/Linux/MYBUILD_427.sym"
Assertion failed: Handler [File:D:/Build/++UE4/Sync/Engine/Plugins/Enterprise/LidarPointCloud/Source/LidarPointCloudRuntime/Private/IO/LidarPointCloudFileIO.cpp] [Line: 281]

[2023.04.03-16.04.46:061][  0]LogCore: Error: appError called: Assertion failed: Handler [File:D:/Build/++UE4/Sync/Engine/Plugins/Enterprise/LidarPointCloud/Source/LidarPointCloudRuntime/Private/IO/LidarPointCloudFileIO.cpp] [Line: 281]

Signal 11 caught.
Malloc Size=65538 LargeMemoryPoolOffset=65554
CommonUnixCrashHandler: Signal=11
[2023.04.03-16.04.46:086][  0]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to write memory at address 0x0000000000000003

[2023.04.03-16.04.46:086][  0]LogCore: Assertion failed: Handler [File:D:/Build/++UE4/Sync/Engine/Plugins/Enterprise/LidarPointCloud/Source/LidarPointCloudRuntime/Private/IO/LidarPointCloudFileIO.cpp] [Line: 281]

0x000000000424a33d MYBUILD_427!UnknownFunction(0x404a33d)
0x0000000004416bbb MYBUILD_427!UnknownFunction(0x4216bba)
0x00000000043bc7e4 MYBUILD_427!UnknownFunction(0x41bc7e3)
0x00000000043bc68b MYBUILD_427!UnknownFunction(0x41bc68a)
0x00000000033a2966 MYBUILD_427!UnknownFunction(0x31a2965)
0x00000000033aa966 MYBUILD_427!UnknownFunction(0x31aa965)
0x000000000472059e MYBUILD_427!UnknownFunction(0x452059d)
0x000000000471b1b7 MYBUILD_427!UnknownFunction(0x451b1b6)
0x000000000471ab0c MYBUILD_427!UnknownFunction(0x451ab0b)
0x000000000472600f MYBUILD_427!UnknownFunction(0x452600e)
0x000000000472e916 MYBUILD_427!UnknownFunction(0x452e915)
0x000000000472dea5 MYBUILD_427!UnknownFunction(0x452dea4)
0x000000000473d071 MYBUILD_427!UnknownFunction(0x453d070)
0x000000000478a6fa MYBUILD_427!UnknownFunction(0x458a6f9)
0x00000000049611aa MYBUILD_427!UnknownFunction(0x47611a9)
0x000000000495f10d MYBUILD_427!UnknownFunction(0x475f10c)
0x00000000081fd5e4 MYBUILD_427!UnknownFunction(0x7ffd5e3)
0x00000000081fa106 MYBUILD_427!UnknownFunction(0x7ffa105)
0x0000000007966f2e MYBUILD_427!UnknownFunction(0x7766f2d)
0x000000000336f92b MYBUILD_427!UnknownFunction(0x316f92a)
0x000000000337de20 MYBUILD_427!UnknownFunction(0x317de1f)
0x0000000008b797f9 MYBUILD_427!UnknownFunction(0x89797f8)
0x00007ff6c02ce083 libc.so.6!__libc_start_main(+0xf2)
0x000000000336eaa9 MYBUILD_427!UnknownFunction(0x316eaa8)

[2023.04.03-16.04.46:090][  0]LogExit: Executing StaticShutdownAfterError
Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
Segmentation fault (core dumped)

-----------------------------------------------------------------
 - OS: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   22C    P8     8W /  70W |    106MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       910      G   /usr/lib/xorg/Xorg                 96MiB |
|    0   N/A  N/A      1036      G   /usr/bin/gnome-shell                8MiB |
+-----------------------------------------------------------------------------+

**Comment by p21nc3** [comment]
[alelav79](https://github.com/alelav79) is it fixed or you still facing this issue?

**Comment by jimcccc** [comment]
Ok

**Comment by mcottontensor** [comment]
The crash doesn't look related to PixelStreaming going by what you provided of the logs. It would be handy if you could provide the full logs of the sessions that crashed if possible.

**Comment by mcottontensor** [comment]
Does not look related to Pixel Streaming.

**Comment by lukehb** [comment]
If it does turn out to be related to Pixel Streaming please use a development build with symbols colocated next to the running binary, a callstack of:

```
0x000000000424a33d MYBUILD_427!UnknownFunction(0x404a33d)
0x0000000004416bbb MYBUILD_427!UnknownFunction(0x4216bba)
0x00000000043bc7e4 MYBUILD_427!UnknownFunction(0x41bc7e3)
0x00000000043bc68b MYBUILD_427!UnknownFunction(0x41bc68a)
```

Does unfortunately tell us very little of where the crash occurs.

**Comment by alelav79** [comment]
Hi,

we have this problem:
https://forums.unrealengine.com/t/lidar-point-cloud-pixel-streaming-plugin-linux-ue-5-1/1167387



thanks for support.

**Comment by lukehb** [comment]
Hi @alelav79, does the point cloud render properly on Linux if you disable the Pixel Streaming plugin?

**Comment by neodr90** [comment]
> Hi @lukehb, even if the pixel streaming plugin is disabled, the point cloud is not rendered.
I think it's just a compatibility problem between the lidar point cloud plugin and linux.

**Comment by lukehb** [comment]
@neodr90 In that case, I will keep the issue closed as it is not related to Pixel Streaming and direct you to UDN or the Unreal Engine forums for support.
