### ISSUE TITLE
How to input Chinese in a input widget?

### ISSUE THREAD

**Issue by zixixr** [EpicGames/PixelStreamingInfrastructure-archived-2024#194]
Hi there,

I created a chatbox in my multi-player PS experience, currently I could only input English on both PC and mobile phones. I can't even copy-paste Chinese in the chatbox. How can I solve it? Thanks.

**Comment by DenisTensorWorks** [comment]
Hi zixixr,

Thank you for submitting this issue. Our team is currently looking into it, it looks like frontend only supports mapping English characters at the moment. We will keep you posted with updates.

**Comment by zixixr** [comment]
Hi @DenisTensorWorks 

Thanks. And even for English characters, there are issues with inputting on mobile devices. You have to use the original input method for ios, and clicking a small type text icon to input.

**Comment by jimcccc** [comment]
Ok

**Comment by chase03** [comment]
https://blog.csdn.net/qq_40544338/article/details/116719305     same issue on Unreal Engine 5.0.3, may this help you, try set localization "zh" package. 
 I have tried this, failed to input Chinese character and only can texting English at this moment according Epic fellow

**Comment by zhangshengsheng** [comment]
That's the problem with me, too

**Comment by zhangshengsheng** [comment]
。。。。。。

**Comment by DenisTensorWorks** [comment]
Reopening this issue as it is still in our backlog to fix. Thank you everyone for your patience with this.

**Comment by AJI1026** [comment]
Same issue
