### ISSUE TITLE
Add unit tests for setting preferred codec and using microphone

### ISSUE THREAD

**Issue by Belchy06** [EpicGames/PixelStreamingInfrastructure-archived-2024#197]
**Component your feature request relates to**
- [ ] Signalling server
- [X] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo

**Problem your feature solves? Please describe.**
With the ability to set preferred codecs as well as add audio tracks to send back to the application, I propose adding unit tests for these features.

**Describe the solution you'd like**
These features can be tested by inspecting the offer/answer and searching for the suitable lines. 

In the case of setting a preferred codec, we should expect this preferred codec to be the first in the SDP.

In the case of using the microphone, we should expect the audio track to be `send/recv`.

**Comment by jimcccc** [comment]
Ok

**Comment by DenisTensorWorks** [comment]
This issue has been move to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/6
