### ISSUE TITLE
[BUG] - If 'num reconnect attempts' setting is > 0, reconnects will be attempted even when a disconnect is triggered by timeout.

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure-archived-2024#203]
**UE Version:**
5.2

**Problem component**
Frontend

**Description**
If `num reconnect attempts` setting is greater than 0, then reconnects will be attempted even when a disconnect is triggered by timeout.

**Expected behavior**
Reconnects should not be attempted when the stream is closed due to timeout.

**Comment by jimcccc** [comment]
Ok
