### ISSUE TITLE
[BUG] - UI Buttons: settingsPanelConfig -> visibilityButtonConfig -> creationMode: 2 => Hides Fullscreen Button

### ISSUE THREAD

**Issue by maxhuawei** [EpicGames/PixelStreamingInfrastructure-archived-2024#205]
**UE Version: **
UE 5.1.1

**Frontend Version: **
@epicgames-ps/lib-pixelstreamingfrontend-ui-ue5.2

**Problem component**
UIOptions for Application - Show / Hide Buttons for Settings and Fullscreen in Frontend

**Description**
By initalizing the Pixelstreaming Player in the webpage and setting the settingsPanelConfig -> visibilityButtonConfig -> creationMode: 2 it does not hide the Settings Button but the Fullscreen button instead. 
(And also the other way round 
fullScreenControlsConfig: { creationMode: 2 } => Hides Settings button.

**Steps to Reproduce:**

const psUIOptions:UIOptions = {
      stream,
      onColorModeChanged: isLightMode => PixelStreamingApplicationStyles.setColorMode(isLightMode),
      settingsPanelConfig: {
        isEnabled: true,
        visibilityButtonConfig: {
          creationMode: 2
        }
      },
      statsPanelConfig: {
        isEnabled: true,
        visibilityButtonConfig: {
          creationMode: 0
        }
      },
      fullScreenControlsConfig: {
        creationMode: 0
      }
    }

    const psApplication = new Application(psUIOptions)

Result is this:
![grafik](https://user-images.githubusercontent.com/109350272/233582072-482d89d5-c89e-4b21-907b-c0b7b1b40b01.png)

**Platform (please complete the following information):**
 - Webtechnology: VUE with NUXT 2 (Typescript)
 - Browser + version:  Firefox, Chrome, Edge
**Additional context**
Thank you for the Pixelstreaming Infrastructure.

**Comment by jimcccc** [comment]
Ok
