### ISSUE TITLE
Use lib-pixelstreamingfrontend, raises player not found error in signalling server

### ISSUE THREAD

**Issue by h12567** [EpicGames/PixelStreamingInfrastructure-archived-2024#206]
**UE Version: **
E.g. UE 5.1.1

**Frontend Version: **
E.g. 0.3.0

**Problem component**
E.g. Signalling Server, Frontend

**Description**

**Steps to Reproduce:**
1. Initiate a PixelStreaming object with the following config 
                    initialSettings={{
                        AutoPlayVideo: false,
                        AutoConnect: true,
                        ss: 'ws://113.22.88.255:91',
                        StartVideoMuted: false,
                        HoveringMouse: false
                    }
 2. 113.22.88.255 is the public ip of the signalling server. 91 is the exposed port for Players
 3. The websocket connection error is terminated. From signalling server log, I observed this `Dropped message iceCandidate cause no player XXX found`.

**Comment by jimcccc** [comment]
Ok

**Comment by lukehb** [comment]
Does this still occur when you use UE 5.2 and frontend version https://github.com/EpicGames/PixelStreamingInfrastructure/releases/tag/UE5.2-0.6.2

?
