### ISSUE TITLE
[BUG] - Matchmaker Redirecting Player to HTTP port when UseHTTP is true

### ISSUE THREAD

**Issue by brookconstantz** [EpicGames/PixelStreamingInfrastructure-archived-2024#207]
**UE Version: **
UE 5.1

**Frontend Version: **
set to _false_ in the config.json for this example

**Problem component**
Signalling Server messaging the Matchmaking Server the wrong config.json attributes

**Description**
If you set HTTPS to _true_ in both the matchmaking and signalling server, then the signalling server will still send the HTTP port instead of the HTTPS port  to the matchmaking server via a _message_. This can cause the redirect from the matchmaking server to the streaming server to fail if you have required HTTPS for all connections.

**Steps to Reproduce:**
1. run matchmaking with your hostname and UseHTTPS: _true_ with the ..\Matchmaker\platform_scripts\cmd\run.bat
2. run the signalling server with UseHTTPS: _true_ and with an open HTTPS port set with the ..\SignallingWebServer\platform_scripts\cmd\Start_SignallingServer.ps1

**Expected behavior**
1. the matchmaking server will redirect users to the HTTPS signaling server port not the HTTP signaling server port

**Platform:**
- Windows Server 2022 (host)
- Player is connecting from an M1 Macbook (Ventura 13.3) using Chrome (112.0.5615.137)

**Potential Solution**
In your ..\SignallingWebServer\cirrus.js , around line 660 inside the following condition " if (config.UseMatchmaker) {...}", go down into matchmaker.on('connect', function() {...} and find the following code before the matchmaker.write(JSON.stringify(message));

Change the following code:

			message = {
				type: 'connect',
				address: typeof serverPublicIp === 'undefined' ? '127.0.0.1' : serverPublicIp,
				port: httpsPort,
				ready: streamer && streamer.readyState === 1,
				playerConnected: playerConnected
			};

to this code:

		if (config.UseHTTPS){
			message = {
				type: 'connect',
				address: typeof serverPublicIp === 'undefined' ? '127.0.0.1' : serverPublicIp,
				port: httpsPort,
				ready: streamer && streamer.readyState === 1,
				playerConnected: playerConnected
			};
		}
		if (!config.UseHTTPS){
			message = {
				type: 'connect',
				address: typeof serverPublicIp === 'undefined' ? '127.0.0.1' : serverPublicIp,
				port: httpPort,
				ready: streamer && streamer.readyState === 1,
				playerConnected: playerConnected
			};
		}

**Comment by jimcccc** [comment]
Ok
