### ISSUE TITLE
lusca requires req.session to be available in order to maintain state

### ISSUE THREAD

**Issue by raufis27** [EpicGames/PixelStreamingInfrastructure-archived-2024#210]
**UE Version: **
UE 5.1.1

**Problem component**
Signalling Server

**Description**
Trying to setup authentication in config file - "UseAuthentication": true - results in an error - "lusca requires req.session to be available in order to maintain state"

How do I solve this problem ?

**Comment by mcottontensor** [comment]
Is this still happening? I tested locally and was unable to reproduce.
