### ISSUE TITLE
Bug: Invisible Cursor

### ISSUE THREAD

**Issue by JRosenschon** [EpicGames/PixelStreamingInfrastructure-archived-2024#22]
There is a problem with the cursor, while using Pixel Streaming.

I'm using Pixel Streaming mainly for Unreal 4.27, but the bug occurs with 5.0 Unreal projects too.
My mouse cursor disappears while using Pixel Streaming.

It doesn’t happen instantly. I can start my App and join a level.
But as soon as I leave the level and go back to the main menu, the cursor turns invisible.
It’s still there, I can hover over buttons, and I am still able to click, but the cursor stays hidden from then on.
It is only fixable by restarting the stream (the app, SWS can keep operating).

If you want to test this. You can easily replicate the issue:
Just create a project using the [Lyra-template](https://docs.unrealengine.com/5.0/en-US/lyra-sample-game-in-unreal-engine/) for Unreal Engine 5.0. I used the current version 5.0.3
Package the project for Windows and run the App + SWS.
In my case, the stream starts as wanted, but the cursor is never visible. You can still control the app with mouse clicks, but you can only guess the cursors position if it hovers over a button.

I'm using the LockedMouse ControlSchemeType.

**Comment by Belchy06** [comment]
Hi @JRosenschon,

I gave this a go just today using the "Top Down" sample from UE5.0.3 and was unable to reproduce the issue.

The cursor is always visible and never disappears.

You may need to set "Show Mouse Cursor" to true on the BeginPlay event of your main menu level.

Let me know how you go!
