### ISSUE TITLE
add "stat PixelStreamingGraphs" to showcase frontend

### ISSUE THREAD

**Issue by MWillWallT** [EpicGames/PixelStreamingInfrastructure-archived-2024#229]
**Component your feature request relates to**
- [ ] Signalling server
- [ ] Frontend library
- [X] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo

**Problem your feature solves? Please describe.**
Currently the "Send Commands to UE" section of the frontend only has "stat fps" and "stat PixelStreaming", however we mention "stat PixelStreamingGraphs" in the showcase application. This helps provide a more "one to one" balance between the application and the frontend.

**Describe the solution you'd like**
Add a "stat PixelStreamingGraphs" button to the "Send Commands to UE" section that toggles the command accordingly.

**Additional context**
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/90592038/d47b22b4-28ea-4bf7-85be-ab3cdd315889)

**Comment by devrajgadhvi** [comment]
Hey there I would like to work on this issue. Can I get this issue assigned to me and also some help regarding what exactly needs to be done?

**Comment by lukehb** [comment]
Yeah, we would be happy to accept a PR from you for this issue.

I don't have cycles to explain exactly what needs to be done, but if you have a look a look at how the `stat pixelstreaming` button works in the `showcase.html`, it is an exact copy and paste of that button/feature except the button should have text that says `stat PixelStreamingGraphs` and should send a message to UE that says `stat PixelStreamingGraphs` too.

Hope that helps :)

**Comment by devrajgadhvi** [comment]
After adding the button the buttons don't fit in same row and hence there comes a horizontal scroll bar which didn't look good. Here is a screenshot of the same
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/32088637/6bb9e0cb-598c-4579-832a-5e06f96b9e5d)

 So I believe I should make it inside a flex and wrap that. After doing so it looks like this should I do it like this? if there are other suggestion do let me know
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/32088637/41fdab1e-e45d-413c-936c-cbee32c59228)

Note: I have also added some space between the row as it wasn't looking good earlier.

**Comment by lukehb** [comment]
Yeah, those styling changes look good to me.

**Comment by devrajgadhvi** [comment]
So I have done changes but I don't currently have resources to test it as it requires UE. Can you help me with testing it. If yes can please let me know what should I do I have made changes in 2 files **showcase.ts** and **./assets/css/showcase.css** Because before creating a PR I wanted to test it once.
Also should I change the text of the button any any specific capitalization? I have added a row-gap of 1vh and it looks good to me now. Below is the screenshot
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/32088637/265f7b57-f799-4e07-86d8-b3b66b23b7e4)

**Comment by lukehb** [comment]
@devrajgadhvi All good, just put together the PR and we can test.

**Comment by devrajgadhvi** [comment]
I've created a PR please test it and revert back.

**Comment by lukehb** [comment]
This may take us a little time, so please be patient, we are in the middle of some other things right now. However, @MWillWallT to test when we resume work on the PSInfra.

**Comment by lukehb** [comment]
Merged.
