### ISSUE TITLE
[Readme] - Container image link doesn't work.

### ISSUE THREAD

**Issue by timbotimbo** [EpicGames/PixelStreamingInfrastructure-archived-2024#231]
**Version:** 
Git branches: master, 5.1 and 5.2

**Problem component**
Github readme

**Description**
The readme (since 5.1) has a **Container images** section that includes a link.
`ghcr.io/epicgames/pixel-streaming-signalling-server` which links to
https://github.com/orgs/EpicGames/packages/container/package/pixel-streaming-signalling-server

Both the text and the link underneath lead me to a 404.

Either the url is incorrect, or it needs account permissions (like access to UE source code).
If the latter, could you add a note that this image is not fully public like the rest of this repo?

**Comment by EpicFailsGames** [comment]
Looks good to me, send to prod @EpicGames/developers

**Comment by mcottontensor** [comment]
Link is behind permissions and will need updating.

**Comment by lukehb** [comment]
@timbotimbo Yes, those container images need you to be part of Epic's Github org so we have added some text mentioning that. https://github.com/EpicGames/PixelStreamingInfrastructure/pull/248
