### ISSUE TITLE
[BUG] - Frontend - Feature MatchViewportRes not quite working.

### ISSUE THREAD

**Issue by antoine-roille** [EpicGames/PixelStreamingInfrastructure-archived-2024#239]
**UE Version: **
E.g. UE 5.1.1

**Frontend Version: **
0.5.1

**Problem component**
Frontend

**Description**
The Flag **MatchViewportRes** doesn't seems to alway do its job, in particular when click and dragging the side of the browser. 

This seems to be caused by the event filtering that is happening here 
https://github.com/EpicGames/PixelStreamingInfrastructure/blob/eea7839f513056ebbd0f98930eb8b8ca895d6bf1/Frontend/library/src/VideoPlayer/VideoPlayer.ts#L213 
(removing that filter fix the problem)

In particular the function referenced by setTimeout seems to never beeing called due to the timeout
https://github.com/EpicGames/PixelStreamingInfrastructure/blob/eea7839f513056ebbd0f98930eb8b8ca895d6bf1/Frontend/library/src/VideoPlayer/VideoPlayer.ts#L232 

Frontend dev is not my speciality so I am not sure why this is hapenning and how to fix it but I'm curious to understand what's going on here.

**Steps to Reproduce:**
1. Set the MatchViewportRes flag to 'true' in the react frontend implementation
2. Start react frontend
3. Resize the window by click and dragging the size of the browser. 
4. Observe the black bands around the video stream (ie the resolution of the stream doesn't match the resolution of the window.

**Platform (please complete the following information):**
 - OS: Windows 11 Pro
 - Chrome Version 113.0.5672.127

**Comment by Magvin** [comment]
Same here. Seems it does ignore resize of any kind
