### ISSUE TITLE
Pixel Streaming HMD -- Convergence is not working as expected

### ISSUE THREAD

**Issue by brycelynch** [EpicGames/PixelStreamingInfrastructure-archived-2024#242]
When enabling pixel streaming plugin in 5.2 and launching a stream with HMD enabled, the stereo convergence rendered in headset is really distorted and not resolving correctly.  Streamer infrastructure is working great (nice job!) and really easy to setup but I'm wondering if there is something not configured correctly for stereo view, or if I've missed something.  Tested using Quest Pro.  

*On Quest 2 the image converges but the FOV is incorrect.

**Comment by lukehb** [comment]
@brycelynch I don't think you have missed anything, I think this is a bug.

Just collating this has also been reported here: 

- https://github.com/EpicGames/PixelStreamingInfrastructure/issues/73#issuecomment-1574250926
- https://github.com/EpicGames/PixelStreamingInfrastructure/issues/73#issuecomment-1569624283
- https://github.com/EpicGames/PixelStreamingInfrastructure/issues/291

We are aware of the issue and considering a fix for 5.3 if possible.

CC @Belchy06

**Comment by lukehb** [comment]
Also reported here: https://github.com/EpicGames/PixelStreamingInfrastructure/issues/291

**Comment by lukehb** [comment]
CC @michaelbecker-d so you get vis on this issue as it moves along.

**Comment by michaelbecker-d** [comment]
hi @lukehb ! just saw 5.3 is in [preview](https://forums.unrealengine.com/t/unreal-engine-5-3-preview/1240016), any chance it includes the fix?

**Comment by lukehb** [comment]
@michaelbecker-d Sorry to say that we don't have a fix in hand yet, so it isn't in 5.3 preview.

**Comment by SerenaDose** [comment]
Hi  @lukehb! Any update on a fix for 5.3?

**Comment by lukehb** [comment]
Sadly not, we have had our priorities shuffled internally. We would be willing to accept/review a PR engine side or frontend side to speed the issue along, but we have been unable to get any internal engineering allocation on this so far due to other things being higher priority. Personally, I would love to get this solved, but we just haven't had the time/approval we need to do so.

**Comment by lukehb** [comment]
For those interested in jumping in to solve the issue I do believe the issue is likely on engine side in the PixelStreamingHMD module that has many hardcoded values and needs to more correctly render an image for the VR headset which is connected on the browser side. It will probably involve sending a custom datachannel payload from the browser to UE to configure the IPD and such values.

**Comment by owu-1** [comment]
Better hardcoded values in the engine module for the Quest 2 are
```
const float ProjectionCenterOffset = 0.09f;
const float HalfFov = 1.6f / 2.f;
```
OpenXR vs Default Pixel Streaming HMD
<details>
<summary>Comparison</summary>
<img src="https://github.com/EpicGames/PixelStreamingInfrastructure/assets/83254308/188e3d5b-54f9-4e07-b396-d2a50bdc7cd3">
OpenXR in grayscale. Default Pixel Streaming HMD in colour.
</details>

OpenXR vs
```
const float ProjectionCenterOffset = 0.09f;
const float HalfFov = 1.5f / 2.f;  // 1.6f is better but I only have an image for 1.5f
```
<details>
<summary>Comparison</summary>
<img src="https://github.com/EpicGames/PixelStreamingInfrastructure/assets/83254308/660bf6d9-b58a-4f02-97eb-cee1ed8eb796">
OpenXR in grayscale. Pixel Streaming HMD with better hardcoded values in colour.
</details>

You can play with whatever determines ViewportSize.X to try and make the image wider.
```diff
diff --git a/Engine/Plugins/Media/PixelStreaming/Source/PixelStreamingHMD/Private/PixelStreamingHMD.cpp b/Engine/Plugins/Media/PixelStreaming/Source/PixelStreamingHMD/Private/PixelStreamingHMD.cpp
index 3735afe..57279ef 100644
--- a/Engine/Plugins/Media/PixelStreaming/Source/PixelStreamingHMD/Private/PixelStreamingHMD.cpp
+++ b/Engine/Plugins/Media/PixelStreaming/Source/PixelStreamingHMD/Private/PixelStreamingHMD.cpp
@@ -110,7 +110,7 @@ void FPixelStreamingHMD::DrawDistortionMesh_RenderThread(struct FHeadMountedDisp
        FRHICommandListImmediate& RHICmdList = Context.RHICmdList;
        const FSceneViewFamily& ViewFamily = *(View.Family);
        FIntPoint ViewportSize = ViewFamily.RenderTarget->GetSizeXY();
-       RHICmdList.SetViewport(0, 0, 0.0f, ViewportSize.X, ViewportSize.Y, 1.0f);
+       RHICmdList.SetViewport(0, 0, 0.0f, ViewportSize.X + 100, ViewportSize.Y, 1.0f);  // Increase amount of picture for eyes. Though modifying this here offsets the right eye so it doesn't do any good

        static const uint32 NumVerts = 4;
        static const uint32 NumTris = 2;
@@ -181,10 +181,10 @@ void FPixelStreamingHMD::CalculateStereoViewOffset(const int32 ViewIndex, FRotat

 FMatrix FPixelStreamingHMD::GetStereoProjectionMatrix(const int32 ViewIndex) const
 {
-       const float ProjectionCenterOffset = 0.151976421f;
+       const float ProjectionCenterOffset = 0.09f;  // Fix eyes converging too far. A straight line is now straight
        const float PassProjectionOffset = (ViewIndex == EStereoscopicEye::eSSE_LEFT_EYE) ? ProjectionCenterOffset : -ProjectionCenterOffset;

-       const float HalfFov = 2.19686294f / 2.f;
+       const float HalfFov = 1.6f / 2.f;  // Fix fov
        TSharedPtr<SWindow> TargetWindow = GEngine->GameViewport->GetWindow();
        FVector2f SizeInScreen = TargetWindow->GetSizeInScreen();
        const float InWidth = SizeInScreen.X / 2.f;
```

**Comment by Belchy06** [comment]
Thanks for providing some hard numbers @owu-1, I'll be sure to give them a try when I've got the HMD out again.

Out of curiosity, do you have a source for the updated values, or were they from trial and error?

**Comment by owu-1** [comment]
No problem and yea it was just trial and error. The workflow to achieve it being
- Open an empty VR template
- Select the camera in the Pawn blueprint and untick Lock to HMD
- Mirror the headset screen to PC with scrcpy
- Use OBS to capture the scrcpy window
- Put the headset into the Oculus link menu
- Optionally disable the proximity sensor so you don't have to keep putting on the headset for the headset's image to display in scrcpy```adb shell am broadcast -a com.oculus.vrpowermanager.prox_close``` https://www.reddit.com/r/OculusQuest/comments/ivc2hr/switch_off_proximity_sensorblack_screen_fix_solved/
- Run the game. Scrcpy should now show the game playing on the headset. The camera should be locked. Change the initial position by moving around Player Start
- In OBS, right click on the scrcpy image and screenshot the source. Import the image into OBS and adjust its opacity and colour correction. This is now the OpenXR reference
- Disable the OpenXR plugin and enable the PixelStreaming plugin. Setup PixelStreamingInfrastructure for VR
- Start Pixel Steaming and note the difference in OBS. Sadly you have to keep putting on the headset to start the stream, but after its started you can put it off if the proximity sensor is disabled

**Comment by demonixis** [comment]
Hey guys,
Do we have a chance to get a fix for 5.4?

**Comment by Belchy06** [comment]
Hey @demonixis,

I can't guarantee anything at this point.

**Comment by ephb** [comment]
Is there any update on this? 
If not would you be open to a PR for this?

**Comment by lukehb** [comment]
@ephb We would be very open to a PR. Likely it is on the UE side, but if you link it here we will review it.

**Comment by DenisTensorWorks** [comment]
Issue is reported to be present on Apple Vision Pro as well (see [issue](https://github.com/EpicGames/PixelStreamingInfrastructure/issues/482) above). 
```
On Apple Vision Pro, the left and right display images are rendered fine on their own, but when viewed through the AVP with both eyes, the resulting image is distorted.

Environment: Apple Vision Pro/Safari/Ubuntu
```

**Comment by ephb** [comment]
Thanks for adding that note. We started work on this specifically with the intent of fixing VisionPro as well.
The issue can reliably reproduced on Quest 3 and we are looking into a fix first.

**Comment by DenisTensorWorks** [comment]
@brycelynch, @michaelbecker-d, @SerenaDose, @owu-1, @demonixis, @ephb 

The issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/7
It should be live shortly, so you can continue following the issue there. Thank you for your contribution!
