### ISSUE TITLE
New Matchmaker documentation page

### ISSUE THREAD

**Issue by MWillWallT** [EpicGames/PixelStreamingInfrastructure-archived-2024#256]
**Component your feature request relates to**
- [ ] Signalling server
- [ ] Frontend library
- [ ] Frontend UI library
- [X] Matchmaker
- [ ] SFU
- [X] This repo
- [X] Docs

**Problem your feature solves? Please describe.**
Currently no specific docs page for matchmaker specific documentation

**Describe the solution you'd like**
Creation of a new docs page that contains any matchmaker specific tips, tricks and guides. This is to keep in line with the new frontend and general documentation.

**Additional context**

**Comment by ShatilKhan** [comment]
Hi @MWillWallT 
Can I work on this issue?
