### ISSUE TITLE
New SFU Documentation page

### ISSUE THREAD

**Issue by MWillWallT** [EpicGames/PixelStreamingInfrastructure-archived-2024#257]
**Component your feature request relates to**
- [ ] Signalling server
- [ ] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [X] SFU
- [X] This repo
- [X] Docs

**Problem your feature solves? Please describe.**
Currently no specific docs page for SFU specific documentation

**Describe the solution you'd like**
Creation of a new docs page that contains any SFU specific tips, tricks and guides. This is to keep in line with the new frontend and general documentation.

**Additional context**

**Comment by ShatilKhan** [comment]
Hi can I work on this issue?
