### ISSUE TITLE
Full screen Issue in IOS safari

### ISSUE THREAD

**Issue by vijodvijay** [EpicGames/PixelStreamingInfrastructure-archived-2024#258]
Both Issue are in IOS safari
UE 5.1.1

Pixel streaming plugin
if you switch the pixel streaming to full screen then it runs as video as video player and the inputs will not work anymore.

In UE 5.2
You can do full screen it doesn't work

**Comment by lukehb** [comment]
CC @Belchy06 this sounds vaguely familiar to me (Matt will not be able to repro on his side)

**Comment by lukehb** [comment]
Hey @vijodvijay - this is fixed in https://github.com/EpicGames/PixelStreamingInfrastructure/pull/266
