### ISSUE TITLE
Add informative intro to the log at the start of a session

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure-archived-2024#272]
**Component your feature request relates to**
- Signalling server

**Problem your feature solves? Please describe.**
It would be useful to have an informative summary at the beginning of a session. See example that SPS utilizes:

```
UE Version:               
Platform:                 linux
Offer from frontend:      false
Instance Port:            8888
Player Port:              1025
Instance IP:              sps-signalling-server-dan-qa-linux-5-2-0
Authentication Plugin:    sps-auth-dan-qa-linux-5-2.tenant-tensorworks-testing.svc.cluster.local:55771
Instance Manager Plugin:  sps-instance-manager-dan-qa-linux-5-2.tenant-tensorworks-testing.svc.cluster.local:55772
Peer Connection Options:  {"iceServers":[{"urls":["stun:stun.l.google.com:19302"]},{"urls":["turn:216.153.61.115:3478"],"username":"sps-coturn-user","credential":"qiuZYmJexj"}]}
```

**Acceptance criteria**
- [ ] I've implemented a summary intro on the UE side
- [ ] I've implemented a summary intro on the PS Infra frontend
- [ ] I've implemented a summary intro on the Signalling Server side

**Comment by mcottontensor** [comment]
Was going to look at this but I realised that the full config is logged when the server starts which covers most of this information. Do we want to print this every time a player joins? Logging is already heavy.
I also don't know what auth plugin and instance manager plugin refers to. I assume this is SPS specific?

**Comment by lukehb** [comment]
I think we can close this as the refactor to signalling will catch this work anyway.
