### ISSUE TITLE
Cannot set min/max bitrate at stream start time from frontend

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure-archived-2024#275]
**UE Version: **
UE 5.2

**Problem component**
Frontend

**Description**
Min/MaxBitrate unable to be set from frontend at stream start time, neither it can be configured during stream running.
It does, however, work if the stream is re-started.

Reason being, UE sends its initial settings message which contains the information about min/max bitrate, which overrides what’s set on the frontend before the frontend has a chance to send its URL values.

For context, if the limitations are added to application launch args instead, i.e. `-PixelStreamingEncoderMaxBitrate=5000`, they work as expected.

Suggested fix is to send this info as a config message.

**Comment by mcottontensor** [comment]
This is a tricky one since the config would need to be sent before the stream starts but we have no connection to the endpoint until the webrtc connection is negotiated and streaming.
Perhaps there is something we can put in the SDP.

**Comment by lukehb** [comment]
I do think when we loop round to this, we should consider putting the metadata into the SDP - that actually seems pretty reasonable considering what we are trying to achieve here.
