### ISSUE TITLE
[BUG] - Signalling Server not responding if accessed through proxy server

### ISSUE THREAD

**Issue by 3DStephen** [EpicGames/PixelStreamingInfrastructure-archived-2024#276]
**UE Version: **
UE 5.0 / NA

**Frontend Version: **
UE 5.0

**Problem component**
Signalling Server

**Description**
Signalling server gives `503 Https Service Unavailable` response when accessed from an external machine using a proxy. A basic web server from `Internet Information Services` Windows feature responds normally and presents its webpage. 

**Steps to Reproduce:**
1. Start Signalling Server using basic Powershell script
2. Verify that you can access the basic template html page using LocalHost (No UE app required)
3. Verify you can access the html page from an external computer with no proxy
4. On the external machine, open the "Proxy" settings in Windows, select "Use a proxy server" under "Manual proxy setup" and configure an Address and Port for a functioning proxy server
5. Attempt to reach the webpage again.

**Expected behavior**
1. Web page should be served up normally

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows Server 2022
 - Browser:  Microsoft Edge...
 

**Additional context**
Reporting this for another user and haven't been able to test yet
HTTP and HTTPS set for port 8000 in Environment Variables
Hosted on AWS g5.4xlarge in us-east-1, in a private VPC
Node JS couldn't be downloaded automatically from the script, so Node version 18.16.0 was installed manually.

**Comment by mcottontensor** [comment]
Trying to reproduce this locally but have so far been unable to.
Do you have any details on the specific proxy being used?

**Comment by DenisTensorWorks** [comment]
Customer has got everything working now (unsure what's changed), so closing as no-repro.
