### ISSUE TITLE
PS frontend will crash the UE project if max bitrate is set lower than min bitrate

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure-archived-2024#278]
**UE Version:**
5.2

**Frontend Version:**
5.2

**Problem component**
Frontend

**Description**
Pixel Streaming frontend will crash UE project if `max bitrate` is set lower than `min bitrate`. Repro rate 100%. Steps to repro:

1. Start a PS-enabled UE project with local arguments
2. Run the SS
3. Connect to localhost
4. Open frontend settings and enter a max bit rate value that is lower than the min bit rate
5. Restart the stream
6. Observe the crash error as the project underneath PS dies

Note that signalling server doesn't actually die, so the application can be restarted and it will run normally.

**Expected behavior**
Frontend should able to handle this scenario whether the user changes it in the configuration menu, or adds the parameters to the URL or send the message directly.

**Screenshots**

![Untitled](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/127062860/9e6ae521-1081-4304-a0c0-ca581649ed81)

**Platform:**
 - Windows 10 Pro
 - Chrome

**Comment by mcottontensor** [comment]
This is an application side issue that will be addressed there.
