### ISSUE TITLE
[Question] XR Pixel Stream from Console to Standalone VR

### ISSUE THREAD

**Issue by Starkium** [EpicGames/PixelStreamingInfrastructure-archived-2024#279]
Would there be a way to use this kind of technology to run the xr pixel stream, for example, on an Xbox to a quest 2? What would be the requirements to get over this hurdle? This could be pretty big for the xr space for consumers who don't have a strong PC and don't want to buy into the PlayStation ecosystem.

**Comment by Belchy06** [comment]
The Pixel Streaming plugin currently only supports running under Windows or Linux, meaning that this use case wouldn't be possible.

That being said, support for running Pixel Streaming on consoles could be added, but it isn't currently on the roadmap.

Cheers

**Comment by Starkium** [comment]
> The Pixel Streaming plugin currently only supports running under Windows or Linux, meaning that this use case wouldn't be possible.
> 
> That being said, support for running Pixel Streaming on consoles could be added, but it isn't currently on the roadmap.
> 
> Cheers

what do you think would be required to make that work on an xbox? (which is essentially windows)

**Comment by Belchy06** [comment]
Hey @Starkium,

You'd need to compile webrtc binaries for xbox compatible with UE and then modify the pixel streaming plugin to both compile and run on this platform.

Additionally, if you're looking to utilise a hardware accelerated video codec, you'd need to also add support this within the AVCodecs plugin.

Cheers
