### ISSUE TITLE
How to run Level Editor Pixel Streaming on Launch

### ISSUE THREAD

**Issue by ExistsMichaelKahn** [EpicGames/PixelStreamingInfrastructure-archived-2024#283]
Hello,
I am currently trying to get the Unreal level editor pixel streaming to start on launch of a project. I have tried using the command -EditorPixelStreamingStartOnLaunch=true, but this gives me the full editor on launch. If anyone has any suggestions I'm listening.

**Comment by Belchy06** [comment]
Hi @ExistsMichaelKahn,

Unfortunately, there's no way to configure the streamed viewport from the command line ([source](https://github.com/EpicGames/UnrealEngine/blob/ue5-main/Engine/Plugins/Media/PixelStreaming/Source/PixelStreamingEditor/Private/PixelStreamingEditorModule.cpp#L104)), although this does sound like a great enhancement that could be made.

I'll get this ticketed and will let you know once it lands in engine.

Cheers!

**Comment by Belchy06** [comment]
Hey @ExistsMichaelKahn,

I'm going to close this now that I've landed this feature in UE5.3, but it'll merge down to ue5-main if you're on that branch. I'll post a link to the commit once it's on Github.

Cheers
