### ISSUE TITLE
docker pull ghcr.io/epicgames/multi-user-server:5.2.1

### ISSUE THREAD

**Issue by Sam6910** [EpicGames/PixelStreamingInfrastructure-archived-2024#284]
**Component your feature request relates to**
- [ ] Signalling server
- [ ] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo

**Problem your feature solves? Please describe.**
A clear and concise description of what the problem is. 

**Describe the solution you'd like**

**Additional context**

**Comment by mcottontensor** [comment]
Need more info. Please fill in the requested details.
