### ISSUE TITLE
How to send a data (descriptor) from web to build (Streamer) and access it in BP ?

### ISSUE THREAD

**Issue by kaelyavel** [EpicGames/PixelStreamingInfrastructure-archived-2024#286]
**Component your feature request relates to**
- [x] Signalling server
- [x] Frontend library

Hello,

I know this is more a question than a feature and I apologize for this but I’m investigating the built-in Pixel Streaming plugin infrastructure and was wondering if there was any was to send a Json string (containing specific info) from the Signalling Web Server (cirrus.js/app.js) to the build (Streamer) and recover that Json from a Blueprint through dedicated nodes (Or ultimately C++) ?

`emitCommand({ "Stat.FPS": '' })` is used in app.js to trigger the 'stat fps' cmd that show the fps on the build side (streamer). I thought about trying to access what’s executed on cmd from a BP but I realized `emitCommand` recognizes specific commands that aren’t necessarily the same on UE. I tried `emitCommand({ "ShowFlag.Splines": '' })` but it didn’t get executed on UE side as there was no output on the cmd contrary to `emitCommand({ "Stat.FPS": '' })` (I use the built-in editor Pixel Streaming feature which allows me to see the output on cmd)

Also, I find it overkill to write a whole new Pixel Streaming delegate in the C++ source files of the plugin to pass custom data to BPs the same way **OnStatChanged** does. Even with that, how to trigger that custom event on the web side ?

I thought about rewriting **OnNewConnection** on C++ side to add a string to it to pass the Json but I was wondering which adjustements I will have to make on the frontend/server to be able to correctly send that  ?

Finally, could this be the answer :

![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/57868366/09e749b1-852c-4271-9527-777dd25dde24)

Apologies again if this shouldn't be posted here.

**Comment by kaelyavel** [comment]
I was on the right track. 

`emitUIInteraction(descriptor) ` in _app.js_ allows you to send a descriptor (Json) that can be recieved on UE side thanks to these nodes : 

![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/57868366/268f9ea7-11ec-47da-a491-5860e3c8268a)

On your _app.js_, just call  `emitUIInteraction(descriptor)` anywhere you want to send data. In this below example, I call it when the show fps UI button is pressed :

```
let showFPSButton = document.getElementById('show-fps-button');
 if (showFPSButton !== null) {
  showFPSButton.onclick = function (event) {
  emitCommand({ "Stat.FPS": '' });
            
  let userData = {
      username : "user01",
      bio : "experimenting Pixel Streaming",
      numberofposts : 2
  }
  emitUIInteraction(userData);
  };
}
```

On UE side, I got : 

![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/57868366/87717551-0cb4-44d5-be8a-6526771842ca)

It would be great if this could be documented in the official docs the same way it was done for the communication from UE5 to the web browser.

I'm closing this and thank you.

**Comment by DenisTensorWorks** [comment]
Thank you for pointing this out, @kaelyavel, we will add this to our docs.
