### ISSUE TITLE
[BUG] - Can't send file nor freeze frame on UE 5.2.1

### ISSUE THREAD

**Issue by kaelyavel** [EpicGames/PixelStreamingInfrastructure-archived-2024#289]
**UE Version: **
UE 5.2.1

**Frontend Version: **
Latest version of branch UE 5.2

**Problem component**
Frontend, Pixel Streaming C++ plugin

**Description**
The 'Send File' node on UE side doesn't work like it used to do. I used it on UE 5.1 and sent images with it to the frontend and I was getting the logs `Received first chunk of file X/N` and the file successfully. After updating UE to 5.2.1, I made sure to use the Frontend version available on the UE 5.2 branch and realized the **Send File** node and the **Freeze Frame** node doesn't work and neither of them log on the frontend or UE (Supposedly should log through `UE_LOG(LogPixelStreaming, Error, TEXT("FileHelper failed to load file data"));` in case the send file fails) 

I can assure I was using correct formatting for the filepath string, MIME type and extension and that the BP nodes gets executed.

**Steps to Reproduce:**
1. Make an Actor BP, add a Send File node to it, fill the inputs and drag it to the level
2. Launch your Signalling Web Server
3. See if you are receiving the file on the frontend end by checking the console tab
4. Nothing happens

**Expected behavior**
1. Receiving logs on the Frontend having the format : `Received first chunk of file X/N`
2. Actually receiving or downloading the file (By changing `a.remove()` to` a.click()` in **FileUtils.ts**)

**Platform**
 - OS: Windows 10 Home 19045.3086
 - Browser Microsoft Edge Version 114.0.1823.67 (Official build) (64-bit)

**Comment by Belchy06** [comment]
Hey @kaelyavel,

This is weird.

I tried to reproduce this today and didn't have the same results, both SendFile and FreezeFrame worked as expected and after the small modification, I was able to automatically download the received file.

Only thing I can think of is that the infra has somehow ended up in a bad state. If you're using git, I'd suggest doing a hard reset with a command like `git reset --hard origin/UE5.2` and then running `./SignallingWebServer/platform_scripts/cmd/setup_frontend.bat --build` to force the frontend to be rebuilt.

Let us know how it goes.

Cheers

**Comment by kaelyavel** [comment]
Hello @Belchy06 ,

Thank you very much for answering my issue and giving me potential solutions.

I indeed did modify the frontend, more specifically the Application.ts (../ui-library) and FileUtils.ts (../library). I tried the hard reset you suggested me but it didn't solve the issue. I also cloned a new copy of the frontend and got the same issue. I did my tests on the 5.2.1 version of the Engine downloaded from the Epic Games launcher aswell as a 5.2.1 version of the Engine built from source (Because I had to switch to it to package a dedicated server) and in both Engine versions the issue remains.

Do you possibly have any other tip I could try out ? Maybe the way I'm entering my fields (path, MIME, extension) is wrong, do you have any specifications about these ? Even though when its fails to send a file, it should log on the console which it doesn't.

All my process is in this 1 minute timelapse video I captured to show you the BP aswell as the state of the frontend. It can be also found on YT : https://youtu.be/_wBOBb4HRKo

https://github.com/EpicGames/PixelStreamingInfrastructure/assets/57868366/f97f410d-17af-49a5-9484-fc01358005b4

Thank you, you and all the team putting out this quality work.

**Comment by kaelyavel** [comment]
https://github.com/EpicGames/PixelStreamingInfrastructure/assets/57868366/da4c9d03-6b32-4da6-bfd6-2e406875a806

**Comment by Belchy06** [comment]
Hey @kaelyavel,

I'm on mobile at the minute so can't offer thorough advice, but having a quick look at the video I think I know what's going on.

Basically, pixel streaming doesn't support play in editor. Even though you're streaming the level editor, this isn't the same as streaming that play in editor session and the underlying streamer logic is a little bit different.

Try launching the game standalone with the necessary pixel streaming args and the send file BP should work. File path, mime type and extension all look good.

**Comment by kaelyavel** [comment]
It works now and I totally get it !

I was streaming the editor (Level window) to the frontend, not the actual game (Play session) and the streaming of the editor doesn't include/consider the (underlying) pixel streaming logic (SendFile/FreezeStream and others) specific to the game running.

A precision : the extension needs to be filled without the '.' (point), otherwise, you'll end up with a file having double points after it's name and before its extension ("_transfer..png_"). Also, I noticed that the name is set by default to '_"transfer"_. Are there any plans to extend the 'SendFile' node to precise the file name after its reception on the frontend ?

Thank you very much @Belchy06 for being extremely responsive and best wishes to you and the team for the development.

**Comment by Belchy06** [comment]
Heya @kaelyavel,

I'm going to close this issue now that we've gotten to the bottom of what was going on.

As for your points about the file extension and default name, we currently have no plans to change the way these operate but adding some safety around checking if the user-specified extension already contains a point won't hurt.

Thank you!
