### ISSUE TITLE
[BUG] - WebXR stereo imaging broken 

### ISSUE THREAD

**Issue by michaelbecker-d** [EpicGames/PixelStreamingInfrastructure-archived-2024#291]
**UE Version: **
E.g. UE 5.2

**Frontend Version: **
No sure

**Problem component**
WebXR stereo imaging is broken on device

**Description**
The device is able to enter WebXR, but rendering is deeply off - feels like the stereo imaging is wrong in a way that's hard to pin down. Repro'd by Alex (@iBrews) and validated by at least one comment on his [video](https://www.youtube.com/watch?v=FqKqews5D90):
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/117380469/ae62f8b2-51a8-4349-bc73-541da27f2916)

**Steps to Reproduce:**
1. Follow Epic's "Pixel Streaming in Virtual Reality" instructions in the experimental pixel streaming [section](https://docs.unrealengine.com/5.2/en-US/experimental-pixel-streaming-features/) of the docs
2. Run on Quest (or, presumably, any other WebXR-capable stereoscopic device

**Expected behavior**
1. Rendering looks fine (it isn't, in a very obvious way)
 
**Screenshots**
Unfortunately very challenging to get screenshots that capture the nature of the problem because casting is mono.

**Platform (please complete the following information):**
 - Oculus Quest Pro 
 - Server running on Windows 11 Pro

**Additional context**

Thank you!

**Comment by lukehb** [comment]
Hi @michaelbecker-d - thanks for reporting this. We are aware of the issue and will be working on a fix when Epic returns from summer break on July 17th.

For now I am closing this particular ticket as we are already tracking this bug here: https://github.com/EpicGames/PixelStreamingInfrastructure/issues/242
