### ISSUE TITLE
[BUG] -  "npm run build"  inside "ui-library " not producing any new "player.js"

### ISSUE THREAD

**Issue by am-abandoned** [EpicGames/PixelStreamingInfrastructure-archived-2024#297]
Branch :
ue5.2

**Screenshots**
<img width="844" alt="image" src="https://github.com/EpicGames/PixelStreamingInfrastructure/assets/28894635/ddde1570-4866-4a53-a4bb-b90ddbcc5342">

**Problem component**
Doc and webpack cmd

**Steps to Reproduce:**
https://github.com/EpicGames/PixelStreamingInfrastructure/blob/UE5.2/Frontend/README.md
accoridng to that doc i have to do this :

> The default user interface is provided in [/ui-library](https://github.com/EpicGames/PixelStreamingInfrastructure/blob/UE5.2/Frontend/ui-library) directory. You can either use it or provide your own user interface. To build the default UI, run:
> 
> cd ui-library
> npm install
> npm run build

**Expected behavior**

> This will produce player.js under the SignallingWebServer/Public directory - this is the default UI.

But i dont see any player.js was produced after excuting "npm run build".

is the doc wrong or i did something wrong ?

**Comment by Belchy06** [comment]
Hi @ahsan-muzaheed,

This looks like the docs are wrong. 

A player.js is only output if you run `npm run build` from one of the `Frontend/implementations` folders.

Let us know if that works for you and we'll get to updating the docs.

Cheers

**Comment by mcottontensor** [comment]
Looks like the docs have been updated for 5.3 onward. I've pulled the changed documentation into 5.2 also.
