### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by vijodvijay** [EpicGames/PixelStreamingInfrastructure-archived-2024#301]
**UE Version: **
E.g. UE 5.2.1

**Frontend Version: **
E.g. UE5.2-0.6.5

**Problem component**
Build is having memory(RAM) leak on server if we run for a long time.

**Description**
Out of memory(RAM). If you keep running the build on cloud (Windows server). It keeps adding up RAM usage and the app crashes.
Its very fast and obvious in development build but very gradual increase in shipping build. And I also found this issue posted by many people in epic forum and other forums.
Its happening more on cloud.
Since pixel streaming keeps running app on cloud for example reserved server this is a major issue.
If you can test a development build you can easily get the issue.

Cloud Specs: G4 2XL dn (Intel Xenon)

**Comment by Belchy06** [comment]
Hey @vijodvijay,

Thanks for bringing this up.

The bug you've reported is actually an issue with the Unreal Engine itself, not the Pixel Streaming Infrastructure. As such, I'm going to close this is issue but don't worry, we are tracking it internally.

Cheers,
Will

**Comment by vijodvijay** [comment]
Please forward it to engine development team
