### ISSUE TITLE
[BUG] - Firefox console errors `TypeError: this.preferredCodec.split is not a function`

### ISSUE THREAD

**Issue by Belchy06** [EpicGames/PixelStreamingInfrastructure-archived-2024#309]
**UE Version: **
UE5-main - source build

**Frontend Version: **
master

**Problem component**
Frontend (possible library)

**Description**
When starting a stream in Firefox, the JavaScript console throws errors about `this.preferredCodec.split` not being a function.

**Steps to Reproduce:**
1. Standard Signalling Server setup
2. Start stream
3. View error in console

**Expected behavior**
No errors

**Screenshots**
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/29305253/037a809d-1114-4c15-b613-ae0489da09e3)

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser + version: Firefox 115.0

**Comment by CreatoonAuraML** [comment]
I have discussed this issue in below thread

https://github.com/markolofsen/metaeditor/issues/48
