### ISSUE TITLE
Unable to set up Player page correctly in UE5.2

### ISSUE THREAD

**Issue by andyng-htech** [EpicGames/PixelStreamingInfrastructure-archived-2024#319]
Hi,

We have been using PixelStreaming in our 5.0 project, with very basic setups as our knowledge in JS is very limited.

Now that we have upgraded the project to 5.2, we understand that the setup is now different as app.js is no longer being used.

Following the documentation on this thread :

https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/Frontend/Docs/Communicating%20from%20UE5%20to%20the%20Player%20Page.md

We were trying to add  "addResponseEventListener("handle_responses", myHandleResponseFunction);" to the player.html page, but the result is that the webpage reflects that "addResponseEventListener is not defined".

We might be missing some steps in between, we are not sure how the player.html in the implementation/EpicGames folder and the Frontend folder all come together, we were changing the player.html inside SignallingWebServer to no avail, and we were having trouble understanding the documentation because of our limited knowledge in the subject. 
Do we need to rebuild the frontend? Do we need to import some other files? We are lost.

Would very much appreciate if someone could point us in the right direction.

**Comment by kaelyavel** [comment]
Hello @andyng-htech,

I'm not from Epic Staff, but I have used the frontend enough to be able to give some answers regarding your issue.

What are you trying to achieve exactly ? Sending an event from the build to the web to trigger something on it ? Such EventListener needs to be written in frontend/ui-library/Application/Application.ts and everytime you make a change to it, you need to delete the Public folder generated in /SignallingWebServer (If generated previously) and do` npm install` / `npm build run` in frontend/ui-library to rebuild again.

I highly suggest you to read the all the .md files inside the repository.

Don't hesitate if you have other questions.

**Comment by Belchy06** [comment]
Hey @andyng-htech,

The documentation you linked mentions adding the response event listener to the PixelStreaming object. I've pushed a custom branch on my fork that illustrates how this can be achieved which can be seen [here](https://github.com/EpicGames/PixelStreamingInfrastructure/commit/e235a60d3dc2549d888f955ed37560ba075f7124).

Once you've made the changes, you'll need to rebuild the frontend. The best way to achieve this is to run either `SignallingWebServer/platform_scripts/cmd/setup_frontend.bat --build` for Windows or `SignallingWebServer/platform_scripts/bash/setup.sh --build` for Linux.

Let us know how you go!

Cheers

**Comment by andyng-htech** [comment]
Hi kaelyavel,

Thanks for the response!

> What are you trying to achieve exactly ? Sending an event from the build to the web to trigger something on it ? 
Yes, that is correct. 

>Such EventListener needs to be written in frontend/ui-library/Application/Application.ts 
In previous versions, we did the code within player.html itself.
So now instead of player.html, we should do it within Application.ts?

**Comment by andyng-htech** [comment]
Hi Belchy,

Thanks for the response!

> The documentation you linked mentions adding the response event listener to the PixelStreaming object. I've pushed a custom branch on my fork that illustrates how this can be achieved which can be seen [here](https://github.com/EpicGames/PixelStreamingInfrastructure/commit/e235a60d3dc2549d888f955ed37560ba075f7124).

So I should be editing the player.ts file, instead of the player.html file?

**Comment by Belchy06** [comment]
@andyng-htech.

The easiest way to achieve what you're trying to would be to modify the player.ts file and then rebuild the frontend.

You can have a look at the commit I linked to see an example of the modifications you could make.

Cheers

**Comment by andyng-htech** [comment]
Hi Belchy

Thank you for you help - issue resolved at long last!! ^^
