### ISSUE TITLE
Running SFU on cloud not working

### ISSUE THREAD

**Issue by vijodvijay** [EpicGames/PixelStreamingInfrastructure-archived-2024#329]
I tried run_local script on cloud it works with local browser 
But when I run, run_cloud and try online it shows video negotiated and stuck there.
I didn't change anything on SFU config or any other files

The streamer app is running pixel streaming -localhost on port 8888

I am running it in aws cloud the default streamer is working but if you make sfu to true this issue happens
Is it any port restriction or do I need to edit IP or something?

Let me know if I need to change anything

**Comment by StomyPX** [comment]
I noticed this happening the other day myself, I'm taking a look into it as I'm pretty sure this is a regression.

**Comment by vijodvijay** [comment]
Please do the fix up and let me know

**Comment by vijodvijay** [comment]
Still waiting for updates

**Comment by StomyPX** [comment]
I've had to prioritize other matters in the meantime so there's no movement on this for the moment

**Comment by Belchy06** [comment]
Hey @vijodvijay,

We tested this last week and everything worked without issue. 

Please have another try and let us know how it goes.

Cheers
