### ISSUE TITLE
[BUG] - NuxtJs imports not compatible

### ISSUE THREAD

**Issue by barbel-thierry** [EpicGames/PixelStreamingInfrastructure-archived-2024#343]
**UE Version: **
UE 5.2

**Frontend Version: **
UE 5.2

**Problem component**
Pixel Streaming

**Description**
When instantiating a WebRtcPlayerController on NuxtJs (2 or 3), an error occurs:
'Event is not defined' from node_modules/@epicgames-ps/lib-pixelstreamingfrontend-ue5.2/dist/lib-pixelstreamingfrontend.js

Basically it seems to inform that the export from PixelStreaming is not compliant to what NuxtJS expects.
The same test is working fine under VueJs (2 or 3) whereas NuxtJs is written on top of VueJs

**Steps to Reproduce:**
1. Setup a new NuxtJs project
2. Instantiate a new object and try to use it:
```
const config = new Config()
const webRtcPlayerController = new WebRtcPlayerController(
    config,
    new PixelStreaming(config)
)

console.log(webRtcPlayerController)
```
3. If the application is served on development (npx nuxt), the 'Event is not defined' error occurs.
If the application is built (npx nuxt build + npx nuxt start), there's no error displayed anywhere (terminal or browser console).

**Expected behavior**
1. Make PixelStreaming compatible with NuxtJs imports.
2. Or at least display a warning in a readme file and when the script is launched.

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Firefox 115.0.3

**Comment by Belchy06** [comment]
Hey @barbel-thierry,

Would you be able to provide us with a minimal repro?

You could do this by pasting your NuxtJS project into your fork of the PixelStreamingInfrastructure in a location such as `Frontend/implementations/NuxtJS` and sending us the link to your fork.

At a quick glance however, you shouldn't need to be interacting with the WebRtcPlayerController directly and should instead be interacting with the `PixelStreaming` class.

Cheers

**Comment by lukehb** [comment]
We are also considering making nuxt.js example using our library - that task is being tracked internally as UE-191779 - we will likely get round to it after 5.3 releases if you want to give us a bump then.

**Comment by barbel-thierry** [comment]
> Would you be able to provide us with a minimal repro?

Here's a minimal [install](https://github.com/barbel-thierry/pixelstreaming-nuxt3) with Nuxt 3

**Comment by copostic** [comment]
Have you tried to use it on `onMounted` ? 

I tried to follow your example and made it work :

```js
<script setup lang="ts">
import { Config, PixelStreaming } from '@epicgames-ps/lib-pixelstreamingfrontend-ue5.2'

onMounted(() => {
  const pixelStreaming = new PixelStreaming(
      new Config()
  )

  console.log(pixelStreaming)
});
</script>
```

**Comment by barbel-thierry** [comment]
I already tried a setup script type and it didn't work. Maybe because I didn't use the lang attribute.

I finally managed to get something starting to work by declaring a plugin with a SSR property set as false:
```js
// nuxt.config.js

{ src: '~/plugins/pixelStreaming', ssr: false }
```
```js
// plugins/pixelStreaming.js

import { Config, PixelStreaming } from "@epicgames-ps/lib-pixelstreamingfrontend-ue5.2";

export default ({ app }, inject) => {
  inject('pixelStreaming', videoConfig => {
    return new PixelStreaming(
      new Config(),
      videoConfig
    )
  })
}
```
And then, calling it like this:
```js
const pixelStreaming = this.$pixelStreaming({
    videoParentElement: videoHtmlElement
})

console.log(pixelStreaming)
```

Thanks a lot for your input!
