### ISSUE TITLE
[Document] - Frontend Version 5.3 How to run on mac?

### ISSUE THREAD

**Issue by rahulcs1988** [EpicGames/PixelStreamingInfrastructure-archived-2024#344]
**UE Version: **
E.g. UE 5.1.1

**Frontend Version: **
E.g. UE5.3-0.3.0

How to run on mac locally? Is there any specific guide guide for it?

**Comment by DenisTensorWorks** [comment]
Thank you for raising the issue @rahulcs1988.
We are currently internally tracking an enhancement request to add mac support and will provide an update when we have one, as well as accompanying documentation.

**Comment by Belchy06** [comment]
Hey @rahulcs1988,

As we've already shipped the release for UE5.3, we won't be adding more features to it. That being said, we've added the required functionality to UE5.4 and master branches, as seen [here](https://github.com/EpicGames/PixelStreamingInfrastructure/pull/389).

The scripts work the same as they would for any other platform so you should be good to go.

Cheers
