### ISSUE TITLE
Multi-Streamer Support documentation [HELP NEEDED]

### ISSUE THREAD

**Issue by andyng-htech** [EpicGames/PixelStreamingInfrastructure-archived-2024#345]
Hi,

I have been searching high and low, but am unable to find any documentations to the Multi-streamer Support added in UE5.2.
Is anyone able to shed some light on this?

**Comment by andyng-htech** [comment]
In 5.2, Multi-streamer Support has been added, stating that it now supports "multiple streamers connected to the same signalling server", and that it makes it possible to "stream local multiplayer experiences".
I would presume by "same signalling server", it would be over one instance of the game.

What is happening now is that I added a Streamer component onto the Player2, and there is a Video Input on the component, which takes in a Back Buffer Streamer Video Input, which I have left at "None"; I would presume it should automatically take the back buffer from the CineCamera on the Player2 itself, but it just doesn't.
On the web browser, even though I subscribed to the Player2 streamer, it is still showing Player1 (DefaultPlayer) view. I was not able to generate multiple streamers.

Might anyone know how to generate multiple streamers on the same game instance?

**Comment by mcottontensor** [comment]
You need valid video inputs for each of the independent streamers. You can have them both using the back buffer video input but then they will both be streaming the same video.
What you most likely want is a separate camera that is rendering to a texture and then use a render target video input to stream the view from that camera.

This video is a great overview of how it works.
https://www.youtube.com/watch?v=OHZ7rZc90ig

**Comment by andyng-htech** [comment]
> You need valid video inputs for each of the independent streamers. You can have them both using the back buffer video input but then they will both be streaming the same video. What you most likely want is a separate camera that is rendering to a texture and then use a render target video input to stream the view from that camera.
> 
> This video is a great overview of how it works. https://www.youtube.com/watch?v=OHZ7rZc90ig

Hi, I am aware of that video, however it is using a Component2D and my UI does not show up on them.

**Comment by mcottontensor** [comment]
Whatever method you are using, you will need to capture the view you want to stream to a texture at some point. How you do that is really out of the scope of Pixel Streaming. Once you have a view rendering to a texture, then you can use the Render Target Video Input to feed that to a streamer.
