### ISSUE TITLE
[BUG] - 5.2 Frontend deadlock states in race conditions

### ISSUE THREAD

**Issue by bramford** [EpicGames/PixelStreamingInfrastructure-archived-2024#347]
**UE Version**
5.2.1

**Frontend Version**
5.2-0.5.3

**Problem component**
Signalling Server, Frontend

**Description**
Frontend enters deadlock state, disconnecting from signalling server, failing to reconnect or not subscribing to DefaultStreamer

**Steps to Reproduce:**
1. Run a large UE project that takes a while to start up (the third person template doesn't seem to be affected by this)
2. Start the signalling server at the same time
3. Start the PixelStreaming client at the same time
4. Race conditions mean that there are often failure cases where the frontend gets stuck.

**Expected behavior**
The frontend should connect to the signalling server, and if it can't, it should retry until it can. If it does connect, and the DefaultStreamer is connected, it should subscribe.

**Platform (please complete the following information):**
 - Kubernetes cluster: Coreweave
 - Browser: Chrome 113.0.5672.92, Firefox & Safari all affected

**Signalling server logs**

PS client deadlocked:
```
14:58:29.232 Running Cirrus - The Pixel Streaming reference implementation signalling server for Unreal Engine 5.2.
14:58:29.239 WebSocket listening for Streamer connections on :8888
14:58:29.239 WebSocket listening for SFU connections on :8889
14:58:29.240 WebSocket listening for Players connections on :8080
14:58:29.240 Http listening on *: 8080
14:58:31.652 Streamer connected: ::1
14:58:31.653 unknown <- {"type":"identify"}
14:58:32.384 __LEGACY__ -> {"type":"endpointId","id":"DefaultStreamer"}
14:58:33.568 player 1 (::1) connected
14:58:33.569 [players] <- {"type":"playerCount","count":1}
14:58:33.810 1 -> {"type":"listStreamers"}
14:58:33.810 1 <- {"type":"streamerList","ids":["DefaultStreamer"]}
14:58:36.055 1 -> {"type":"listStreamers"}
14:58:36.055 1 <- {"type":"streamerList","ids":["DefaultStreamer"]}
14:58:38.298 1 -> {"type":"listStreamers"}
```
Refresh browser a minute later (which restarts PS client) and it works:
```
14:59:32.780 DefaultStreamer -> {"type":"ping","time":1691679572}
14:59:33.564 player 1 connection closed: 1001 -
14:59:33.564 [players] <- {"type":"playerCount","count":0}
14:59:44.868 player 2 (::ffff:127.0.0.1) connected
14:59:44.868 [players] <- {"type":"playerCount","count":1}
14:59:45.110 2 -> {"type":"listStreamers"}
14:59:45.111 2 <- {"type":"streamerList","ids":["DefaultStreamer"]}
14:59:45.354 2 -> {"type":"subscribe","streamerId":"DefaultStreamer"}
14:59:45.354 DefaultStreamer <- {"type":"playerConnected","playerId":"2","dataChannel":true,"sfu":false,"sendOffer":true}
14:59:45.394 DefaultStreamer -> 2 {"type":"offer","sdp":"v=0\r\no=- 1773298194546598230 2 IN IP4 127.0.0.1\r\ns
```
Different browser which worked on the first try:
```
23:55:57.400 Running Cirrus - The Pixel Streaming reference implementation signalling server for Unreal Engine 5.2.
23:55:57.406 WebSocket listening for Streamer connections on :8888
23:55:57.406 WebSocket listening for SFU connections on :8889
23:55:57.407 WebSocket listening for Players connections on :8080
23:55:57.407 Http listening on *: 8080
23:55:59.584 Streamer connected: ::1
23:55:59.585 unknown <- {"type":"identify"}
23:55:59.681 __LEGACY__ -> {"type":"endpointId","id":"DefaultStreamer"}
23:56:12.042 player 1 (::1) connected
23:56:12.042 [players] <- {"type":"playerCount","count":1}
23:56:12.291 1 -> {"type":"listStreamers"}
23:56:12.291 1 <- {"type":"streamerList","ids":["DefaultStreamer"]}
23:56:12.541 1 -> {"type":"subscribe","streamerId":"DefaultStreamer"}
23:56:12.541 DefaultStreamer <- {"type":"playerConnected","playerId":"1","dataChannel":true,"sfu":false,"sendOffer":true}
23:56:12.590 DefaultStreamer -> 1 {"type":"offer","sdp":"v=0\r\no=- 2163605696654549536 2 IN IP4 127.0.
```

**Comment by samuel-ward** [comment]
I was able to reproduce this on a basic Third Person template project, with the pixel streaming plugin enabled.

If you run the uiless web client, signalling server, and Unreal project at the same time the project will connect to the signalling server, and connects over WebRTC, but the web client will never play the stream.

- [Web Client Logs](https://drive.google.com/file/d/1bGVYgBFVfP-slQXzYCu72-xvXeHMxJFe/view?usp=sharing)
- [Signalling Server Logs](https://drive.google.com/file/d/17hkHqZbR4R-pO_niwlTgjtl9WLE57HBk/view?usp=sharing)
- [Unreal Project Logs](https://drive.google.com/file/d/1QZtxIXzuOa5-230c37wWnsIUySkuZV-g/view?usp=sharing)

If the Unreal project is running and connected to the signalling server before the web client connects then this will not occur.

**Comment by DenisTensorWorks** [comment]
@bramford, we've just made a commit attempting to fix this problem: https://github.com/EpicGames/PixelStreamingInfrastructure/pull/358

Could you try and see if it resolves your problem? Thank you!

**Comment by samuel-ward** [comment]
@DenisTensorWorks I've tested the above changes.
This does solve the issue where the uiless client connects to the signalling server before the pixel-streaming client (Unreal), however I've seen that if you have the uiless client is running prior to the signalling server it won't connect to the pixel-streaming client.

- [Web Client Logs](https://drive.google.com/file/d/1r45B5m0-CEprddluhIJ8gANcJwUD8_sp/view?usp=sharing)
- [Signalling Server Logs](https://drive.google.com/file/d/1ylzBGUiDVjz95UW9RPCC9EOTpm22w-g9/view?usp=sharing)
- [Unreal Project Logs](https://drive.google.com/file/d/1PpjI25N_R_fc6JHNWScm3vN7I5ms4nOs/view?usp=sharing)

If the signalling server is running before either of the other two clients this works well.

**Comment by MWillWallT** [comment]
Thank you for your information towards this issue Sam.

As the fix has resolved the initial problem, we'll close this issue here. 

Regarding the Uiless client running prior to the signalling server, this is resolved via a simple page refresh, so shouldn't be blocking.

If the original issue here remains, please provide reproduction steps to produce a deadlocked state (e.g. a state where no further connections will be accepted).

If there is a separate issue to the above, please open a new issue.

Thank you!
