### ISSUE TITLE
Cannot build docker SFU server on MacOS

### ISSUE THREAD

**Issue by zaku33** [EpicGames/PixelStreamingInfrastructure-archived-2024#348]
**Component**
- [ ] Signalling server
- [ ] Matchmaker
- [x] SFU

**About the issue**
- Currently , I can run SFU server on Win 10 but cannot run on MacOS.
- Already test on Win 10, work as expect with `run_local.bat`. Not try to build it with Docker but it's okay.

**Evidence**
![Screenshot 2023-08-14 at 14 30 12](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/38272907/20b766f9-5a77-4e1c-897f-63ae14bf2901)

**Notice**
- I've already downgraded node from v20.5.1 -> v16.4.2 (same as node version run on Win 10) but still not working ( error same as image above )

**Comment by mcottontensor** [comment]
Unfortunately the package for the SFU uses some platform dependent resources and MacOS is not supported. You might have luck by changing references to 'mediasoup_prebuilt' in package.json and sfu_server.js and trying to install/run again.
I have a forked branch here https://github.com/mcottontensor/PixelStreamingInfrastructure/tree/sfu_no_prebuilt that contains those changes.
Hopefully this will work for you. We will look at adding MacOS support in a future change.
