### ISSUE TITLE
UE5.2[BUG] - Cannot Show Mouse Cursor in Pixel Stream

### ISSUE THREAD

**Issue by HadesViolet** [EpicGames/PixelStreamingInfrastructure-archived-2024#349]
**UE Version: **
E.g. UE 5.1.1

**Frontend Version: **
UE5.2

**Problem component**
Signalling Server 

**Description**
I am unable to show mouse cursor in game I can only use browser mouse or hover mouse.

**Comment by lozn00** [comment]
same problem

**Comment by StephenYoung007** [comment]
same problem，the developers said that this problem would be fixed in UE5.2, but still as we can see

**Comment by Khroz** [comment]
I actually have Mouse Cursor on my Pixel Stream setup, it took a while to make it work but here is the blueprint in case anyone is interested.

https://blueprintue.com/blueprint/6uafylco

**Comment by MWillWallT** [comment]
Hi guys,

If you were looking to have a visible, in-game cursor during Pixel Streaming, whilst also having locked mouse, you can do so via:

Enable the Unreal Engine software cursor:

1. Open Project Settings > Engine - User Interface > Software Cursors.
2. Add a new software cursor (click the + icon) and you'll see 2 dropdown fields.
3. In the first field, select "Default".
4. In the second field select "DefaultCursor".
5. Save project.

Then, ensure your PlayerController has "Show cursor" enabled, as shown here:
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/90592038/7db32ada-d81f-4413-b7ce-6cde4e70503a)


That should ensure a visible software cursor you can use regardless of hovering or locked mode in stream.

**Comment by AmbitionGan** [comment]
Hello everyone, the pixels are being rendered on the front end but you can't select the actor and you can't move them, anyone
