### ISSUE TITLE
[BUG] - Mouse sensitivity is different between large resolution / ultra wide frontend and standard 1080p

### ISSUE THREAD

**Issue by adrian-j-programmer** [EpicGames/PixelStreamingInfrastructure-archived-2024#351]
**UE Version: **
E.g. UE 5.2.1

**Problem component**
Pixel Streaming Input

**Description**
In projects where mouse axis input is used to pan the camera, the perceived mouse sensitivity is different between ultra-wide, 4k and 1080p resolutions. 

**Steps to Reproduce:**
1. PixelStream the Third Person Example project to a local browser tab when display resolution is set to standard 1920x1080
2. Repeat step 1 with ultra-wide display resolution
3. Repeat step 1 with display resolution set to 4k
4. Notice mouse sensitivity of camera panning increases the higher the display resolution is

**Expected behavior**
Mouse sensitivity is the same regardless of the display resolution used by stream receiver. 

**Platform (please complete the following information):**
 - Windows 11 Home 22H2
 - Firefox 116.0.3

**Comment by HadesViolet** [comment]
Hi @adrian-j-programmer I am having the same problem. Are you talking about the resolution of the application or the general resolution of the monitor?

**Comment by adrian-j-programmer** [comment]
@HadesViolet We use the new dynamic resolution feature, so the resolution of the application adjusts to the stream viewport size. The issue seems to be connected to the resolution of the monitor somehow.

**Comment by HadesViolet** [comment]
Thank you

**Comment by adrian-j-programmer** [comment]
Reopen

**Comment by DenisTensorWorks** [comment]
@adrian-j-programmer, @HadesViolet 

The issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/9
It should be live shortly, so you can continue following the issue there. Thank you for your contribution!
