### ISSUE TITLE
[BUG] - Stalled performance on UE5.2.1

### ISSUE THREAD

**Issue by Aeddon** [EpicGames/PixelStreamingInfrastructure-archived-2024#353]
**UE Version: **
UE 5.2.1

**Frontend Version: **
UE5.2-0.6.5 Release

**Problem component**
unkown

**Description**
We’re using pixel streaming in production.
We have a perfect performance with 5.0.3, even just out of the box without tweaking anything. Now we are experimenting with 5.2.1, where quite some stuff about pixel streaming has changes, or should I say has been improved?

But we’re facing massive troubles with performance.
We see the stream is not fluid anymore, but stalls every few seconds for quite some frames.
We see massive package losses that never have been there before, and all this even with a very strong GPU on the server.
If we set the rendering on the server not to be headless, and connect to the machine with a remote desktop tool (Teradici) we can see that the user input is arriving flawlessly, and everything is rendering perfectly smooth and without freezes, but at the same time on the pixel stream client (same host where the Teradici client is running), there are these freezes.

    Has anybody of you experienced something similar?
    Has anybody experience in debugging such symptoms?

To see the Teradici client providing an absolute flawlessly & fluid rendering at the same time as the pixel streaming client in the browser (tested several different browser, all the same) shows these freezes indicates that it can’t be a network issue or latency…

We’ve played around with measuring GPU RAM and load, added more system RAM and vCPUs (even though they never showed a bottleneck there), and checked many different nvidia GPUs. Maybe I need to add that we’re on Linux.

But the problem seems to persist everywhere. Only when we reduce the render resolution to a very very low value, it seems to get better… We also played with bandwidth and quantization parameter, but it doesn’t really help.

**Steps to Reproduce:**
We can provide a clone of the machine for testing/reproducing. Let me know

**Expected behavior**
flawlessly & fluid rendering & encoding & transporting to the browser like it was working good in 5.0.3

**Platform (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - Several browsers affected
 - tested Chrome 116.0.5845.112, Firefox 116.0.3

**Comment by mcottontensor** [comment]
We have not noticed anything similar to this. Can you provide more details on the situation you are facing? What codecs are you using? What parameters are you running with? Have you done any cvar customizations related to pixel streaming?
Could you provide video of the issues you are facing?
The more details you can give the easier it is for us to narrow it down.

**Comment by mcottontensor** [comment]
I noticed that this has also been posted to UDN where the discussion has already begun. I'll close this issue here so we don't split up the information focus. We can follow up on UDN.

**Comment by CreatoonAuraML** [comment]
Actually I am doing pixel streaming of unreal engine game, so I am using pixel streaming infrastructure for this provided by unreal.

Now what happens is when I start streaming in the browser by visiting the streaming url

The streaming looks really  fine in the starting, now after some time might be 13 minutes (time is not definite), the quality of the streaming video turns down to low and after some time streaming freezes and then finally websocket connection gets closed and no streaming happens then

I dont know why, but I have seen some behaviours which are mentioned below

1) Stream does not freezes when the streamer is connected to standalone mode of game in unreal, it only freezes when I am using its packaged version (.exe) file

2) GPU video decoder shows a sharp spike after some time when the game freezes and eventually game crashes
