### ISSUE TITLE
[BUG] - When a user double-clicks, UE doesn't receive the second release

### ISSUE THREAD

**Issue by DenisTensorWorks** [EpicGames/PixelStreamingInfrastructure-archived-2024#359]
**UE Version: **
E.g. UE 5.2.1

**Problem component**
Frontend

**Summary**

In 5.2.1, when a user double-clicks, the second release is never received by UE. A user reports having to work around this by sending a release input action manually when their frontend detects a double click.

**Description from the user**

Input in the Pixel Streaming Demo example project works just fine. It uses the same input logic we use in our project to toggle camera pan (hold LMB to pan camera). 

In our project, we also handle doubleclick natively (LMB bound to IE_DoubleClick) to select where our character is supposed to move. When we use the vanilla 5.2 pixel streaming infra, this is what happens:
1. We double click to move our character.
2. Our character moves, but camera panning is enabled afterwards without any buttons being held

Our team has discovered that this issue goes away after commenting out the body of [this function](https://github.com/EpicGames/PixelStreamingInfrastructure/blob/20dd81f606f08e052db374e18e0a565b9827e91e/Frontend/library/src/Inputs/HoveringMouseEvents.ts#L158).

What we ended up doing as a workaround is our frontend sends a mouse up event a short time after the double click event. This fixes the issue of our camera getting stuck at panning after double click.

**Expected behavior**
UE should be able to correctly handle double-clicks and register release events

**Environment:**
- Frontend: 5.2
 - OS: (TBC)
 - Browser: Chrome and Firefox

**Comment by lukehb** [comment]
We can probably use the top down project to repro this, it has click to move controls out of the box I believe.

**Comment by DenisTensorWorks** [comment]
The issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/10
