### ISSUE TITLE
[BUG] - Gesture interaction does not work in UE5.1 with iOS

### ISSUE THREAD

**Issue by kjs1715** [EpicGames/PixelStreamingInfrastructure-archived-2024#376]
**UE Version:** 
UE 5.1.1

**Frontend Version:** 
UE5.2

**Problem component**
Frontend, Pixel Streaming C++ plugin

**Description**
Gestures such as pinch and zoom (and even single click) does not work with Enhanced Input and raw input in iOS devices but work in android device. What I noticed while debugging is the blueprint node "Get Touch Input State" will output "Is Pressed" to be false from iOS and be true from android.

**Platform (please complete the following information):**
 - Test Device: iPhone 13 Pro, iPad Pro 12.9, Samsung Z Flip 5
 - Streaming OS: Windows 10 Enterprise (Version: 21H2)

**Comment by oxzzx** [comment]
UE Version:
UE 5.2.1

Frontend Version:
UE5.4-0.0.1

Description
Encountering the same problem

Platform (please complete the following information):

Test Device: iPad Pro A2228  iPadOS version16.3.1 
Streaming OS: Windows 10 Pro (Version: 22H2)
