### ISSUE TITLE
emitUIInteraction in react

### ISSUE THREAD

**Issue by caoyichi** [EpicGames/PixelStreamingInfrastructure-archived-2024#377]
In the epic guide (app.js and webRtcPlay.js), I can use emitUIInteraction directly.

In react demo, it just show how to display a unreal engine in react component.
I wonder how to use   streaming.emitUIInteraction()  with the server in react component.

**Comment by caoyichi** [comment]
I can addResponseEventListener and get responses.
still, I can not send a  message through emitUIInteraction()

**Comment by caoyichi** [comment]
I solve this problem by change 5.4 to 5.3

**Comment by lukehb** [comment]
Okay, if the issue is resolved now, I will close,
