### ISSUE TITLE
[BUG] - Gamepad not recognized

### ISSUE THREAD

**Issue by Khroz** [EpicGames/PixelStreamingInfrastructure-archived-2024#378]
**UE Version:**
UE 5.2.1

**Frontend Version:**
[UE5.2-0.6.5](https://github.com/EpicGames/PixelStreamingInfrastructure/releases/tag/UE5.2-0.6.5)

**Problem component**
Gamepad

**Description**
I've been trying to set up gamepad (xbox one controller) for Pixel Streaming, but with no luck. The keyboard and mouse works as expected both in local and when in stream session, the gamepad works as expected in local only.
1. First i noted that it wasnt functioning because gamepads only work on browsers via secure context (HTTPS) so i made the SSL Setup.
2. When i move the sticks for the first time in the gamepad i can move and look but no other mapped buttons work, if i close the window and open again i get an error message saying that webkit gamepad is a vendor specific function and its deprecated and it should be changed to the not vendor specific one and it gets stuck walking forever. If restart the streamer and try from another computer with the same gamepad it shows me a second error saying .toFixed is undefined.

I tried to attach as many screenshots as possible.

**Steps to Reproduce:**
VM SIDE
1. Upload your build to your VM
2. Run TURN/STUN + Signalling Server
4. Run Streamer App

CLIENT SIDE
1. Connect Xbox Controller to Computer
1. Open Chrome, type the Address to hit VM in Chrome / Mozilla
2. Get access to the stream
4. Move the stick for the first time i can move the sticks but no console logs from unreal and the controller bp i set up as if it is not detecting the mapped buttons, no warning messages in the browser except for the webkit specific vendor flag.
6. Close Chrome
7. Open Chrome again
8. Type the address again
9. Connect to Stream
10. Move stick then i get a warning message saying cant get the prevState and it stucks walking forward forever.

If i restart the streamer app in the vm side and try the same steps from another computer with the same hardware and sofware specs i just get a .ToFixed is undefined and it wont even move and look.

**Expected behavior**
1. I would expect to connect to the session.
2. Be able to use the gamepad to control the session as when in local.

**Screenshots**
![gamepadtests02](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/50791774/35595a09-2687-4953-8567-0eb5f25972ac)

![gamepadtests01](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/50791774/f8e98836-c605-45ff-905c-e85569579c0e)

![buguegamepad02](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/50791774/1c6c5045-470b-46f4-a59f-85bcce267b97)

**Platform (please complete the following information):**
VM
OS: Windows 10 (win10-22h2-pro-g2 image)
Client Machine
OS: Windows 10 (64 bit)
Browser: Chrome: Version 117.0.5938.132 (64 bit)
Browser: Mozilla: Version 118.0.1 (64 bit)
Gamepad
XBox One Driver Version 5.17.3202.0

**Additional context**
- I dont have a multiplayer setup, mainly we use the app to showcase to clients so only the presenter is connected to the stream during the presentation.
- I've been debugging this for days so i started to think that maybe it dont detect the session because it counts the client as a player 2 so, maybe it asigns an empty gamepad controller? Would love light on this as we need to deliver this asap.
- I'm running the app with the flag for rendering offscreen.

**Comment by Khroz** [comment]
Still testing on why is the gamepad not working with the pixel stream + ssl config.

**Comment by Belchy06** [comment]
Hey @Khroz,

I've done some testing with gamepads recently which has led to a few PRs and bug fixes:
1. `GamepadButtonReleased` not being triggered: https://github.com/EpicGames/PixelStreamingInfrastructure/commit/87b9c9aaed39b2e00e6a6654d406140dfce8f028
2. Fix warnings about being unable to set the previous state https://github.com/EpicGames/PixelStreamingInfrastructure/commit/606298d40d6157386e908ac1c6ae1181f0dfc6ce

I haven't tackled the SSL issue, so let me know how your testing goes!

Cheers
