### ISSUE TITLE
[BUG] - emitUIInteraction is not received in unreal

### ISSUE THREAD

**Issue by zvaehn** [EpicGames/PixelStreamingInfrastructure-archived-2024#391]
**UE Version: **
UE 5.3.1

**Frontend Version: **
  // working
  "@epicgames-ps/lib-pixelstreamingfrontend-ue5.3": "^0.0.2",
  "@epicgames-ps/lib-pixelstreamingfrontend-ui-ue5.3": "^0.0.3",

  // Not working
  "@epicgames-ps/lib-pixelstreamingfrontend-ue5.3": "^1.0.0",
  "@epicgames-ps/lib-pixelstreamingfrontend-ui-ue5.3": "^1.0.0",

**Problem component**
the function emitUIInteraction is not working in 5.3-1.0.0, but works totally fine if i downgrade to 5.3-0.0.3

**Description**
Function returns true, but no data is received in unreal.

**Screenshots**
![blueprint-playerinput](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/5555821/bf7ae018-9bc8-47b8-8e84-996fd0c50f7b)

**Platform (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: 118.0.5993.71 (64-Bit)

**Comment by timbotimbo** [comment]
This commit ["Fix emitUIInteraction method"](https://github.com/EpicGames/PixelStreamingInfrastructure/commit/70e15a166f48493a560a6c9820a8a5f1047d71ca) was added to the 5.3 branch after the 1.0.0 release.

Looks like it is fixed in the git repo but has not yet been released in a package update.

**Comment by oblivionxs** [comment]
5.4-0.0.1 have this problem too

**Comment by mcottontensor** [comment]
5.3 and 5.4 have new releases today. Please check that these issues are fixed.

**Comment by oblivionxs** [comment]
> 5.3 and 5.4 have new releases today. Please check that these issues are fixed.
yes，I have passed the test

test versions
ue5.3 1.0.1
ue5.4 0.0.2

**Comment by zvaehn** [comment]
it only works sometimes for me. Some events are send, some not.
