### ISSUE TITLE
[BUG] - stream full editor happen all operator locked

### ISSUE THREAD

**Issue by mail555** [EpicGames/PixelStreamingInfrastructure-archived-2024#413]
**UE Version: **
E.g. UE 5.2.1-0+UE5

**Frontend Version: **
E.g. UE5.2-0.6.5

**Problem component**
E.g. Frontend

**Description**
from toolbar Pixel Streaming, click stream full editor, when click open level from menu file, will all can't click

**Steps to Reproduce:**
1. install UE plugin Pixel Streaming
2. start SignallingWebServer from PixelStreamingInfrastructure UE5.2-0.6.5
3. start stream full editor from toolbar Pixel Streaming
4. visit http://127.0.0.1, open dialog new level from menu file, will happen all lock, and operator nothing 

**Screenshots**

**Platform (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Browser + version [e.g. chrome 118.0.5993.118]

**Comment by mcottontensor** [comment]
If you are starting the signalling server menually. Be sure to click "Use remote signalling server".
If you do not do this, the editor will create it's own signalling service and connect to it.

**Comment by mail555** [comment]
yes,i click "Use remote signalling server",but problem still happen,when open dialog for example new level from menu file,will all browser screen can't operate.

**Comment by mail555** [comment]
device info
CPU:AMD Ryzen 7 5700X 8-Core Processor
GPU:AMD Radeon RX 6600

output log
LogPixelStreaming: Error: Selected codec was not a supported codec, falling back to negotiating codecs...

**Comment by mcottontensor** [comment]
Looking at the dialog behaviour there are a few states where actions can become blocked through the stream.
- If the dialog is minimized there's no way to bring it back
- If the dialog is maximized the stream completely freezes and no input is evident.
- Dragging the dialog using its titlebar does not work. Could be the source of other issues.

@Belchy06 I'm not sure if you're aware of these issues. Your input might be needed here.

**Comment by Belchy06** [comment]
I'm aware of this issue.

The reason it's happening is due to some application level wrapping that takes place on the UE side whenever the cursor enters the webpage.

Unfortunately, in its current state, you can have an user controlling from the browser or a user controlling from UE, never both.

This is tracked and will be done once other, higher priority, matters are taken care of.

**Comment by DenisTensorWorks** [comment]
@mail555

The issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/11
It should be live shortly, so you can continue following the issue there. Thank you for your contribution!
