### ISSUE TITLE
LogPixelStreaming: Warning: Pixel Streaming audio component will not tick because Pixel Streaming module is not loaded. 

### ISSUE THREAD

**Issue by TANKCHENG** [EpicGames/PixelStreamingInfrastructure-archived-2024#42]
LogPixelStreaming: Warning: Pixel Streaming audio component will not tick because Pixel Streaming module is not loaded. This is expected on dedicated servers.

It happend when i use PixelStreaming model in Linux, and Pixel Streaming model not working.

**Comment by lukehb** [comment]
This is to be not related to the frontend but the Pixel Streaming C++ code - i.e. you will note that log message is not in this repo. I appreciate your bug report, but I will ask you to file it through the official channels - either UDN or here: https://forums.unrealengine.com/c/general/feedback-requests/
