### ISSUE TITLE
[BUG] - stream full editor happen all operator can't do

### ISSUE THREAD

**Issue by mail555** [EpicGames/PixelStreamingInfrastructure-archived-2024#421]
**UE Version: **
E.g. UE 5.2.1-0+UE5

**Frontend Version: **
E.g. UE5.2-0.6.5

**Problem component**
E.g. Frontend

**Description**
from toolbar Pixel Streaming, click stream full editor, when click open level from menu file, will all can't click

**Steps to Reproduce:**
1. install UE plugin Pixel Streaming
2. start SignallingWebServer from PixelStreamingInfrastructure UE5.2-0.6.5
3. "Use remote signalling server" from toolbar Pixel Streaming
4. start stream full editor from toolbar Pixel Streaming
5. visit http://127.0.0.1, open dialog new level from menu file, will happen all lock, and operator nothing 

**Screenshots**

**Platform (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Browser + version [e.g. chrome 118.0.5993.118]

**Comment by mcottontensor** [comment]
Reopened #413
