### ISSUE TITLE
Black screen only on Android devices

### ISSUE THREAD

**Issue by sautechgroup** [EpicGames/PixelStreamingInfrastructure-archived-2024#423]
**UE Version: **
UE 5.1.1

**Frontend Version: **
UE5.1

**Description**
Hello everyone. I have a project that I play in streaming from editor by using the external Pixel streaming Signalling server available from this repository.
It works from pc and IOS devices, but from Android devices it does not work as expected. When I click on "Click to start" then play button it remains on black screen.
I tried to start the "Start_WithTURN_SignallingServer" but nothing changed.
I tried with the last version of PixelStreamingInfrastucture, and it goes stuck on "WEBRTC CONNECTED, WAITING FOR VIDEO" display.
It does not work neither from the same network nor other networks.

I can give you additional information if you need.
Thank you.

UPDATE
Tried with Android 10 version and it works, it does not work with Android 12 and 13 (11 not tested)

**Comment by mcottontensor** [comment]
I have tested with a Samsung Galaxy S21 on Android 13 using editor streaming and "Start_WithTURN_SignallingServer" with no issues. This was on a local network.
Is there any further information on the Android device you are using? The black screen issue usually means the streamer is unable to make a connection to the browser. Perhaps there's some kind of fire walling going on or the network configuration is different?
