### ISSUE TITLE
Should AutoConnect and Autoplay work in Chrome when VideoMuted set

### ISSUE THREAD

**Issue by erikgalajda** [EpicGames/PixelStreamingInfrastructure-archived-2024#424]
**Component your feature request relates to**
- [ ] Signalling server
- [ ] Frontend library
- [x] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo

**Problem your feature solves? Please describe.**
AutoPlayVideo=true&AutoConnect=true&StartVideoMuted=true shows the play button in chrome, is there any way to make it pass autoplay Chrome browser policy?

**Describe the solution you'd like**
Autoplay/AutoConnect works in chrome.

**Additional context**

**Comment by mcottontensor** [comment]
Using your given URL parameters here I was able to auto connect and auto play a stream OK. Perhaps you have additional settings or plugins that are preventing it?

**Comment by erikgalajda** [comment]
In my case I am getting this from `lib-pixelstreamingfrontend.esm.js`:
```
Level: Log
Msg: NotAllowedError: play() failed because the user didn't interact with the document first. https://goo.gl/xX8pDD

Level: Log
Msg: Browser does not support autoplaying video without interaction - to resolve this we are going to show the play button overlay.
```

Did you test in chrome? Is the auto play policy active on your site? It works in firefox for example.

**Comment by erikgalajda** [comment]
Just found out there has been a [fix](https://github.com/EpicGames/PixelStreamingInfrastructure/pull/407) for that.
