### ISSUE TITLE
Stuck in "Starting connection to server, please wait" 

### ISSUE THREAD

**Issue by ZQlby** [EpicGames/PixelStreamingInfrastructure-archived-2024#43]
for the problem above, i search this article below:
https://dev.epicgames.com/community/learning/tutorials/VY4X/unreal-engine-where-s-my-stream-turn-server-debugging-for-pixel-streaming
and found out where is the bug. thx for that.

the turn server is indeed not relaying as expected, 
even i force using turn in chrome, 
and it doesnt work just as the article informed, 
my ue project on cloud is 4.27 version.
<img width="1680" alt="Screen Shot 2022-11-03 at 13 49 59" src="https://user-images.githubusercontent.com/28595778/199655312-33ab0678-c58f-44dd-b18c-17fa571d6357.png">

So what is next, how can i fix this issue? 
let me know if i miss anything that might help.🌹

**Comment by ZQlby** [comment]
is it possible that i didnt set public ip manually in scripts or somewhere cause this bug?

**Comment by ZQlby** [comment]
it work somehow last night...wired...and unstable

**Comment by lukehb** [comment]
This issue tracker is for tracking issues with the front end js/servers. For debugging ICE connections please use the official channels such as UDN.
