### ISSUE TITLE
[BUG] - Frontend settings in URL are case sensitive

### ISSUE THREAD

**Issue by MWillWallT** [EpicGames/PixelStreamingInfrastructure-archived-2024#430]
**UE Version: **
UE 5.3.2

**Frontend Version: **
UE 5.3

**Problem component**
Frontend settings

**Description**
Setting frontend settings such as match viewport resolution, hovering mouse mode and lightmode are case sensitive in the URL.
For example, adding `/?HoveringMouse=true` to your URL works, but `/?hoveringmouse=true` does not.

**Steps to Reproduce:**
1. Start a basic local pixel stream
2. Add a lowercase frontend setting to the URL, e.g. /?hoveringmouse=true
3. Observe setting failing to set.

**Expected behavior**
Frontend settings should function as intended, regardless of casing in URL.

**Platform (please complete the following information):**
 - OS: Windows 10 + Ubuntu
 - Chrome, Firefox and Edge

**Additional context**

**Comment by DenisTensorWorks** [comment]
The issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/12
