### ISSUE TITLE
How to input Chinese in a input widget

### ISSUE THREAD

**Issue by Shooter-oss** [EpicGames/PixelStreamingInfrastructure-archived-2024#433]
I want to know how to input Chinese in PixelStreaming

**Comment by DenisTensorWorks** [comment]
Hi @Shooter-oss, the issue is already opened [here](https://github.com/EpicGames/PixelStreamingInfrastructure/issues/194) and we are tracking it.
We've unfortunately not been able to prioritize it, but it is on our radar.
Thank you for your patience with this.
