### ISSUE TITLE
[BUG] - Local stream is not working in Firefox (WebRTC connection negotiated)

### ISSUE THREAD

**Issue by marospekarik** [EpicGames/PixelStreamingInfrastructure-archived-2024#435]
**UE Version: **
UE 5.3

**Frontend Version: **
UE5.3

**Problem component**
Signalling Server, Frontend, Pixel Streaming C++ plugin?

**Description**
I just upgraded my UE project and pixel-streaming-infrastructure to UE5.3, and I am unable to access the stream in the latest Firefox. The stream is working properly in Chrome. Everything runs locally. 

**Steps to Reproduce:**
- Run`Start_WithTURN_SignallingServer` with default config
- Run Pixel-Streaming in Unreal Engine Editor
- Run any example from the Frontend library

**Expected behavior**
1. Both browsers should be supported or any additional setup should be given

**Screenshots**
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/14806065/f2c1470e-9dba-41ea-a50d-08894e7ebb17)

**Platform (please complete the following information):**
 - OS: Win
 - Firefox v119.0.1

**Comment by mcottontensor** [comment]
The steps work locally here. Do you get the same result if you just run the run_local.bat script for the signalling server?
The shown screenshots are usually the result of the player being able to connect to the signalling server, but the streamer and player cannot create an ICE connection and talk to eachother. This might be an issue with the TURN configs locally.

**Comment by marospekarik** [comment]
Thanks for that, there was something strange with my setup, after restarting the machine, the stream works also in Firefox. Sorry for this premature report, closing for now.
