### ISSUE TITLE
[BUG] - Firefox Regression (120) - glitchy/laggy stream

### ISSUE THREAD

**Issue by timbotimbo** [EpicGames/PixelStreamingInfrastructure-archived-2024#440]
**UE Version:**
N / A

**Frontend Version:**
5.2, 5.3, 5.4

**Problem component**
Browser or WebRTC ?

**Description**
Since today, all my streams start laggy with green flashes.
The stream connection and framerate in the stats still appear to be fine.

I replicated this on multiple versions of the Signalling server and Unreal Editor and all behaved the same.
- PixelStreaming demo UE 5.2 and UE 5.3
- Signalling server branch 5.2, 5.3 and 5.4

I tested these browsers
- Chrome (119.0.6045.160) works fine ✔️
- Edge (119.0.2151.72) works fine ✔️
- Firefox (120.0)  Shows the issue ❌
- (downgraded) Firefox 119 Works fine ✔️

Which means an automatic firefox update is the culprit.

**Steps to Reproduce:**
1. Run a PixelStreaming Unreal project, I used the official demo.
2. Start the signalling server (local)
3. Disable all browser plugins
4. Visit localhost in the browser
5. Start the stream
6. On Firefox the stream will be glitchy, on other browsers it will be normal.

It does not happen 100% of the time, but I've been able to reproduce it dozens of times.

**Expected behavior**
1. No regression in the latest Firefox.

**Screenshots**
The difference between Firefox 120 and 119, visiting the exact same Pixelstreaming config.

https://github.com/EpicGames/PixelStreamingInfrastructure/assets/11444698/9bfa1f61-a6e2-4a65-81cf-86ac0d72ec37

https://github.com/EpicGames/PixelStreamingInfrastructure/assets/11444698/b5820489-96c8-4b99-ac63-76ccbc2c3925

**Platform (please complete the following information):**
 - OS: Windows 10
 - For browsers see description above.

**Additional context**
This might just be a browser bug that you can't fix, but it still helps to figure out exactly what's broken.

**Comment by DenisTensorWorks** [comment]
@timbotimbo, thank you for the detailed info and the attachments, this is super helpful. We are looking into it.

**Comment by marospekarik** [comment]
I am experiencing the same issue. Additionally, the quality control is toggling continuously every few seconds and I am getting this error:```Level: Error
Msg: Provided message data doesn't match expected layout. Expected [  ] but received [  ]```

**Comment by timbotimbo** [comment]
Firefox 120.0.1 mentions something possibly related in the [changelog](https://www.mozilla.org/en-US/firefox/120.0.1/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-desktop&utm_campaign=about-dialog).
> Fixed an issue that was causing YouTube videos to show a green screen when hardware acceleration was enabled. ([bug 1865928](https://bugzilla.mozilla.org/show_bug.cgi?id=1865928))

Just tested this version and I can't replicate the issue right now.
So this is either fixed or at least massively improved.

**Comment by DenisTensorWorks** [comment]
For record - this bug is still occurring for several users, and we suspect it is on FireFox side, so it has been logged in [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1874349)
