### ISSUE TITLE
How to specify the streaming codec for my standalone streamer app?

### ISSUE THREAD

**Issue by zhuchenyang** [EpicGames/PixelStreamingInfrastructure-archived-2024#456]
I can't find relevant documentations.
In the Editor, I can specify the encoder type for the streaming.
![1214](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/2928729/cd69ad45-8398-42b7-a9c0-452abe29def5)

But I can't find the documents for how to specify it for my standalone streamer app.
I,ve tried two different ways.
First is trying -PixelStreamingEncoder='VP9' when I start my streamer application like this:
Myapp.exe -PixelStreamingEncoder='VP9' -PixelStreamingEncoderMaxQP=10 -AudioMixer -PixelStreamingIP=127.0.0.1 -PixelStreamingPort=8888 -AllowPixelStreamingCommands -RenderOffScreen -Unattended
However, in the official documents, there is no such a arguments called "PixelStreamingEncoder"....

Second is adding "PreferredCodec="VP9"" in my frontend code like this:
```
// Create a config object
const config = new Config({
  initialSettings: {
    AutoPlayVideo: true,
    AutoConnect: false,
    ss: "ws://10.1.56.103:8080",
    WaitForStreamer: true,
    MatchViewportRes: true,
    HoveringMouse: true,
    SuppressBrowserKeys: false,
    ControlsQuality: true,
    PreferredCodec: "VP9"
  },
  useUrlParams: false,
});
```

I can't know wether does it works or not. There is no significant changes.

**Comment by Belchy06** [comment]
Hey @zhuchenyang,

You can launch your Unreal Engine application with `PixelStreamingEncoderCodec=VP8|VP9|H264`.

The only way to set the used codec is on the application side, setting the codec on the frontend just signals to the application that it would prefer that codec, but doesn't guarantee that it will actually get used.

Cheers
