### ISSUE TITLE
How to solve the mouse offset problem on devices with different resolutions?

### ISSUE THREAD

**Issue by leleshuo** [EpicGames/PixelStreamingInfrastructure-archived-2024#457]
**UE Version:**
E.g. UE 4.27

**Problem component**
Mouse offset problem on devices with different resolutions

**Expected behavior**
Mouse coordinates can be accurately matched on displays with different resolutions

**Comment by DenisTensorWorks** [comment]
Hi @leleshuo, this issue is being tracked [here](https://github.com/EpicGames/PixelStreamingInfrastructure/issues/351). 
Feel free to add any information that can be useful to the original issue and thank you for you patience while we resolve it.
