### ISSUE TITLE
在不同的分辨率显示器上，鼠标会发生偏移

### ISSUE THREAD

**Issue by leleshuo** [EpicGames/PixelStreamingInfrastructure-archived-2024#458]
**UE Version:**
E.g. UE 4.27

**Description**

**Expected behavior**
像素流可以准确匹配鼠标坐标

**Comment by DenisTensorWorks** [comment]
Hi @leleshuo, this issue is being tracked [here](https://github.com/EpicGames/PixelStreamingInfrastructure/issues/351). 
Feel free to add any information that can be useful to the original issue and thank you for you patience while we resolve it.
