### ISSUE TITLE
[BUG] - Provided message data doesn't match expected layout

### ISSUE THREAD

**Issue by ZhangFan-1999** [EpicGames/PixelStreamingInfrastructure-archived-2024#459]
**UE Version:**
E.g. UE 5.1.1

**Frontend Version:**
E.g. UE5.3-0.3.0

**Problem component**
@epicgames-ps/lib-pixelstreamingfrontend-ue5.4
@epicgames-ps/lib-pixelstreamingfrontend-ui-ue5.4

**Description**
When opening the browser console and using the mouse to swipe back and forth between the pixel flow interface and the browser console, the mouseEnter and mouseLeave events will be triggered, or when the mouse moves to the button on the page, this issue will also occur
It does not affect the playback of pixel streams, but the console keeps reporting errors

**Expected behavior**
how to resolve this error

**Screenshots**
![Snipaste_2023-12-15_11-34-52](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/57339879/ac0c6f48-3919-4c15-84dd-66b7a31d5b72)

**Comment by ohayak** [comment]
I m encountering same bug using same configurations

**Comment by DenisTensorWorks** [comment]
@ZhangFan-1999, @ohayak

The issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/13
It should be live shortly, so you can continue following the issue there. Thank you for your contribution!
