### ISSUE TITLE
KeyboardEvent.keyCode is Deprecated

### ISSUE THREAD

**Issue by xosg** [EpicGames/PixelStreamingInfrastructure-archived-2024#46]
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

`Deprecated: This feature is no longer recommended. Though some browsers might still support it, it may have already been removed from the relevant web standards, may be in the process of being dropped, or may only be kept for compatibility purposes. Avoid using it, and update existing code if possible; see the [compatibility table](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode#browser_compatibility) at the bottom of this page to guide your decision. Be aware that this feature may cease to work at any time.`

**Comment by lukehb** [comment]
CC @Belchy06 - could you take a look at this one?
