### ISSUE TITLE
[BUG] - Not able to access the pixel streaming in office laptop  (WebRTC connection negotiated)

### ISSUE THREAD

**Issue by rahulzephyr** [EpicGames/PixelStreamingInfrastructure-archived-2024#460]
**UE Version:**
E.g. UE 5.2

**Frontend Version:**
E.g. UE5.2

**Problem component**
E.g. Signalling Server, Pixel Streaming

**Description**
I have hosted the pixel streaming in the AWS EC2 instance (Windows server 2022, g4dn.2x large family instance type). Using the public IP address of EC2 I could access the streaming in my private devices (personal laptop and mobile device) but not able to access the same in my office laptop. As this is part of my office project it is expected to access the streaming in the office laptop as well. 

In my laptop I have created the inbound and outbound rule allowing all ports as well but still no luck :( 

**Error:**
I am getting the error like "WEBRTC CONNECTION NEGOTIATED"

![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/53375028/9de88c98-69e9-4b53-9cfa-d98bf3decac2)

Since I was getting error in port 80 while running the file Start_WithTURN_SignallingServer, I changed it to HttpPort: 90 in config.json (earlier even when it was working in port 80 the issue was there).

Is this something I need to check with my office IT security team to unblock something or some work around can be done in Pixel streaming itself?

It would be really helpful if someone help me resolve this.
Thanks in advance!!

**Comment by wurenand** [comment]
same problem

**Comment by brookconstantz** [comment]
I used pixel streaming to run an interactive survey for a school research project. I'd say about 5% of my participants had this issue you sharing, I think if either network blocks some of the negotiation it gets stuck. This issue was more common on government networks. I did not figure out a workaround except for telling them to use a home network instead.

**Comment by rahulzephyr** [comment]
Yes same with me as well. I cannot access it in my office network or if my laptop is connected to a VPN. I don't know if I make it as an HTTPS-secured connection, it will work. Can someone provide some information on this?

**Comment by missge9** [comment]
In my case, the "WEBRTC CONNECTION NEGOTIATED" error was an AWS security problem.
I simply allowed all incoming rules. Which is certainly not optimal. But it works like this
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/53297559/b8982d89-b09e-4d60-bbe7-693f9ae13191)
and for https. I have a linux Nginx server that manage the certificate, which then redirects to the AWS private IP
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/53297559/4af90e91-15d6-47de-9014-388c3565987c)

**Comment by DenisTensorWorks** [comment]
@rahulzephyr, @wurenand, @FogDrip, @missge9  

The issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/14
It should be live shortly, so you can continue following the issue there. Thank you for your contribution!
