### ISSUE TITLE
 Unable to input Chinese characters

### ISSUE THREAD

**Issue by TongMatin** [EpicGames/PixelStreamingInfrastructure-archived-2024#461]
Unable to input Chinese characters , compositionEndHandler Unable to trigger

 const compositionEndHandler = (ev) => this.handleOnCompositionEnd(ev);
        const keyDownHandler = (ev) => this.handleOnKeyDown(ev);
        const keyUpHandler = (ev) => this.handleOnKeyUp(ev);
        const keyPressHandler = (ev) => this.handleOnKeyPress(ev);
        document.addEventListener("compositionend", compositionEndHandler);
        document.addEventListener("keydown", keyDownHandler);
        document.addEventListener("keyup", keyUpHandler);
        //This has been deprecated as at Jun 13 2021
        document.addEventListener("keypress", keyPressHandler);
        this.keyboardEventListenerTracker.addUnregisterCallback(() => document.removeEventListener("compositionend", compositionEndHandler));
        this.keyboardEventListenerTracker.addUnregisterCallback(() => document.removeEventListener("keydown", keyDownHandler));
        this.keyboardEventListenerTracker.addUnregisterCallback(() => document.removeEventListener("keyup", keyUpHandler));
        this.keyboardEventListenerTracker.addUnregisterCallback(() => document.removeEventListener("keypress", keyPressHandler));

**Comment by gunsha** [comment]
@TongMatin can you test with my branch to see if it works? i have a pending [pull request](https://github.com/EpicGames/PixelStreamingInfrastructure/pull/442) for this
https://github.com/gunsha/PixelStreamingInfrastructure/tree/master
