### ISSUE TITLE
[BUG] - Right Eye Only Has 1/3 and Really Bad Resolution

### ISSUE THREAD

**Issue by ffreality** [EpicGames/PixelStreamingInfrastructure-archived-2024#462]
**UE Version:**
5.3.1 Epic Launcher Version

**Frontend Version:**
Both Master and Release UE5.3-1.0.1

**Description**
When I enable PixelStreaming, right eye is not completely black but I can see only 1/3 of right eye on both Unreal Editor and Meta Quest Browser (Immersive WebVR View).

Resolution is really bad.

**Steps to Reproduce:**
1.  I did `Pixel Streaming in Virtual Reality` steps from
https://docs.unrealengine.com/5.3/en-US/experimental-pixel-streaming-features/

2. I am not using VRTemplate and its Pawn. I have a PlayerCharacter which I use all on my other projects. 
I deleted all of OpenXR related functions. Right now it has only Motion Controller Components, VRCameraRoot and VRCamera.

3- I also try VRTemplate to just test it.

4- I disabled Instance Stereo Render, Mobile HDR, Forward Rendering.

**Expected behavior**
1- An acceptable resolution (not same level with Quest Link but better than current)
2- I can see both eye at the same time

**Screenshots**
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/10528447/7be67159-16d7-4a84-ab10-15db8b183015)

**Platform (please complete the following information):**
 - OS: Windows 11 Pro
 - Meta Quest Browser (Latest Updates Installed)
 - Oculus Quest Pro with Latest Updates

**Additional context**
My notebook is an Asus Rog which has AMD Ryzen 9 5900HX with APU and RTX 3080. It doesn't have complete APU disable feature on Asus Armory Crate. Quest Link doesn't have problem with it but can this be related with APU ?

For resolution, I have 16Gbit WiFi 6E Router. Quest Pro connected to 6GHZ 6E channel and my notebook 5 GHZ WiFi 6 Channel. So, It shouldn't be a network problem.

**Comment by MWillWallT** [comment]
Hi there!

I've reproduced this issue, we're having a look into it now.

**Comment by ffreality** [comment]
> Hi there!
> 
> I've reproduced this issue, we're having a look into it now.

you rock !

**Comment by joshgrundmeier** [comment]
Adding to this - have tested across Quest 2, Quest Pro, & Quest 3 all see the same issue as what @ffreality has posted. Have gotten slightly better outcomes with "-ResX, - ResY" to the point where I can get both eyes very close, but once there the FOV is way too wide, and to get it to be stereoscopic you need to cross your eyes slightly.

**Comment by ffreality** [comment]
> Adding to this - have tested across Quest 2, Quest Pro, & Quest 3 all see the same issue as what @ffreality has posted. Have gotten slightly better outcomes with "-ResX, - ResY" to the point where I can get both eyes very close, but once there the FOV is way too wide, and to get it to be stereoscopic you need to cross your eyes slightly.

I don't think HMD device or PixelStreamingInfastructure make the difference.
If I could see correct view in viewport, maybe we could say it's about them but even everything closed, right eye is problematic.

I thought it was about
- desktop renderer on mobile rhi (roadmap has some entries about it)
- optimizations like foveations (focusing specific side of render to increase performance ??)

I say this because (I know they are not related and just speculations but) interchange framework refactor affected datasmith dataprep. So, we know that some changes can also break other things.

and you can't say "be a squint" to your customers :D 

btw. As I know Apple Vision Pro won't have pc tethering like Quest Link but we can use WebXR with it.
So, fixing this will also open that device to UE users when they want to make a big scene like digital twins.

**Comment by joshgrundmeier** [comment]
with the added resolution arguments I can get the right eye to be very close to matching the left in the browser window, however - depending on the HMD, they all displayed slightly differently, thus the reason to bring them up.

**Comment by ffreality** [comment]
> with the added resolution arguments I can get the right eye to be very close to matching the left in the browser window, however - depending on the HMD, they all displayed slightly differently, thus the reason to bring them up.

Oh, okay sorry. I talked about 1/3 right eye problem. Yes, device and correct resolution arguments are important for quallity. Actually high end devices like Varjo or Apple can be much more susceptible.

**Comment by DavidLopezS** [comment]
I'm running into the same issue. Is there any improvement or still the same situation?

**Comment by DavidLopezS** [comment]
Tried the same case in version 5.2.1 and it seems the 1/3 issue got solved there.

**Comment by ffreality** [comment]
> Tried the same case in version 5.2.1 and it seems the 1/3 issue got solved there.

There are tutorial videos about VR pixel streaming on YouTube and all of them published at 5.2 times. If there was problem before, they would tell.

**Comment by DavidLopezS** [comment]
I've been testing with different versions of UE, and in UE 3.0 for oculus (https://github.com/Oculus-VR/UnrealEngine) I get a correct view of Pixel Streaming VR when running as "Standalone Game". Though when building and running the .exe I stomb into the same "1/3 view in the right eye" problem. I dunno if this case may be useful or has been tested already, but it's a strange case IMO.

**Comment by ffreality** [comment]
> I've been testing with different versions of UE, and in UE 3.0 for oculus (https://github.com/Oculus-VR/UnrealEngine) I get a correct view of Pixel Streaming VR when running as "Standalone Game". Though when building and running the .exe I stomb into the same "1/3 view in the right eye" problem. I dunno if this case may be useful or has been tested already, but it's a strange case IMO.

How is resolution of oculus branch ? btw as I know pixel streaming use virtual hmds and requires disabling openxr and other device specific things. So, we shouldn't even use Oculus branch for pixel streaming at first place. Or am I wrong ?

**Comment by ffreality** [comment]
issue continues with 5.3.2

**Comment by DenisTensorWorks** [comment]
@ffreality, @joshgrundmeier, @DavidLopezS 

The issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/16
It should be live shortly, so you can continue following the issue there. Thank you for your contribution!
