### ISSUE TITLE
Support for multiple streams under same peer connection

### ISSUE THREAD

**Issue by OOOllie** [EpicGames/PixelStreamingInfrastructure-archived-2024#468]
**Component your feature request relates to**
- [ ] Signalling server
- [ ] Frontend library
- [ ] Frontend UI library

**Problem your feature solves? Please describe.**
Having to create multiple tabs to receive multiple video streams is not efficient. User should be allowed to configure multiple streams of data in the same browser tab.

**Describe the solution you'd like**
Enable customizability to allow one player to subscribe to multiple streams at once over the same peer connection. 

**Additional context**
This may require modification to the Pixel Streaming Plugin. I've been searching for a solution to add multiple Streamer instances to a player but I cannot find this.

**Comment by lukehb** [comment]
Having multiple video streams from the same peer connection would indeed require a modification to the Pixel Streaming plugin. The specific modification would be to support multiple video tracks to be added to each streamer/peer connection on the UE side.

While feasible, this is not on our roadmap at all. We would be willing to accept a PR on the Unreal Engine repo potentially, but this not something we are focusing on supporting any time soon.
