### ISSUE TITLE
WebCam feed

### ISSUE THREAD

**Issue by DrRaedAbbas** [EpicGames/PixelStreamingInfrastructure-archived-2024#47]
Hi,
I've very interested in receiving webcam feeds from remote user(s) as a texture in Unreal that I can use in a material or widget. Is there a way to achieve this using the native Pixel Streaming plugin or do I still need to find a third party solution?

**Comment by lukehb** [comment]
Webcam feeds coming in is not supported today. 

However, in 5.1 video decoding support was added into PS for VP8/VP9. So potentially if you were to enable to webcam input in the javascript frontend and then use the experimental "Pixel Streaming Player" plugin that was released in 5.1 I think it should be possible to display the webcam feeds as materials/textures in UE.

**Comment by DrRaedAbbas** [comment]
That logic is pure music to my ears. The problem is that I am not a JavaScript developer unfortunately. Any help/direction would be much appreciated

**Comment by lukehb** [comment]
If you follow the code path for useMic it should be similar set of steps to request webcam media from the browser and then add it as a track to the peer connection (similar to what is done with audio track and useMic)
