### ISSUE TITLE
[BUG] - Incorrect rendering on Apple Vision Pro (VR)

### ISSUE THREAD

**Issue by bryanhpchiang** [EpicGames/PixelStreamingInfrastructure-archived-2024#482]
**UE Version:**
5.3

**Frontend Version:**
I used https://github.com/EpicGames/PixelStreamingInfrastructure/commits/master/ at commit 5cf2735c5fb4c7f84fea7ec41ea72befb2cecbe8

**Problem component**
Unclear

**Description**
Convergence issues for pixel streaming with VR on the Apple Vision Pro. The left and right display images are rendered fine on their own, but when viewed through the AVP with both eyes, the resulting image is distorted.

**Steps to Reproduce:**
1. Follow the tutorial [here](https://www.youtube.com/watch?v=CyrWKI0FKDk) to start the server
2. On the Apple Vision Pro, open Safari
3. Visit the public IP

**Expected behavior**
1. A clear image seen with both eyes

**Screenshots**

**Platform (please complete the following information):**
 - OS: Ubuntu

**Additional context**

**Comment by DenisTensorWorks** [comment]
Thank you for reporting the issue @bryanhpchiang and providing additional environment details.
The issue is being tracked here https://github.com/EpicGames/PixelStreamingInfrastructure/issues/242 and I've added your additional details to the thread.
