### ISSUE TITLE
[BUG] - streamerIDOption.selected returns an array. Not a string

### ISSUE THREAD

**Issue by vinkovsky** [EpicGames/PixelStreamingInfrastructure-archived-2024#489]
**UE Version:**
UE 5.4

**Frontend Version:**
UE5.4-0.0.3

**Problem component**
Frontend

**Description**
I want to continue the topic raised [here](https://github.com/EpicGames/PixelStreamingInfrastructure/commit/649d6b2dcb42e0f0db1aaaa85fc47efac656b0de#r138409735)
Tested the ability to connect several streamers to one signal server, without using a matchmaker. An array of available streamers comes to the client via a web socket, and everything is cool here. 
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/66293881/52a876ad-0c1b-4f03-922d-08545af504b1)

The problem appears when selecting a streamer during initial setup.
```ts
    initialSettings: {
           StreamerId: 'DefaultStreamer1'
     }
```

The StreamerId parameter is not accepted in the PixelStreaming class and no connection to the streamer occurs. 
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/66293881/6e8db6cb-e2a4-47a7-9491-e754aea6b088)

This only works if you specify the /?StreamerId=DefaultStreamer1 parameter via the URL
![image](https://github.com/EpicGames/PixelStreamingInfrastructure/assets/66293881/198eb5b4-1f96-47fc-bafe-121d63ea2a35)

Updating In SettingOption.ts in the constructor
```ts
    super(id, label, description, [defaultTextValue], defaultOnChangeListener);
```
to
```ts
    super(id, label, description, defaultTextValue, defaultOnChangeListener);
```

fixed this issue (Thanks @mcottontensor)

**Steps to Reproduce:**
1. Clone React example and pass StreamerId: 'DefaultStreamer1' (or your streamer's name) option to Config
2. Run two streamers on the same 8888 ports 
3. Start the signalling web server and configure it to listen two streamers on the 8888. Only one signaling server required!
4. Try connecting to the stream from the client (You won`t succeed)
5. At this point go to WebRtcPlayerController.ts -> handleStreamerListMessage method and try to log streamerIDOption.selected. 

As mentioned in [SettingsOption.ts selected() getter must return a string](https://github.com/EpicGames/PixelStreamingInfrastructure/blob/e91781b6fa81c0d3149661557a461dafd87cc16c/Frontend/library/src/Config/SettingOption.ts#L95). But here it is an array of strings. Typescript won't tell you the error, you have to check the console. Because of this, the condition does not work correctly and the wanted streamer is not assigned to a variable

Here is a piece of code from [WebRtcPlayerController.handleStreamerListMessage()](https://github.com/EpicGames/PixelStreamingInfrastructure/blob/e91781b6fa81c0d3149661557a461dafd87cc16c/Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts#L1323)
```ts
      //Oh, why is there var here???
      var streamerIDOption = this.config.getSettingOption(OptionParameters.StreamerId); // <--  Here is an array !!
      const existingSelection = streamerIDOption.selected.toString().trim(); // <-- Here is a string. Its ok
      if (!!existingSelection) { // <-- Cool, we're inside an if statement
            // default to selected option if it exists
            wantedStreamerId = streamerIDOption.selected; // <-- OMG. Here is an array !!
      }
      
      .... 
      
      ....
                                                         // (sh*t, here is an array) conditions go wrong
      if (wantedStreamerId && messageStreamerList.ids.includes(wantedStreamerId)) {
            // if the wanted stream is in the list. we pick that <-- (will be cool, but ['Streamer', 'Streamer1'].includes(['Streamer']) returns false)
            autoSelectedStreamerId = wantedStreamerId;
```
This also doesn't work correctly if there is only one streamer but with a specified StreamerId on the client. 

**Expected behavior**
1. The stream must run through the selected StreamerID.

**Platform (please complete the following information):**
 - OS: Ubuntu Desktop 22.04.3 LTS
 - Chrome Version 121.0.6167.160 (Official Build) (64-bit)

P.S. Many thanks for your hard work. You've created a really great library.

**Comment by mcottontensor** [comment]
Added to master, will be in 5.4
