### ISSUE TITLE
[BUG] - Mic sound is not streamed from MacOS browsers to UE app

### ISSUE THREAD

**Issue by vlobzakov** [EpicGames/PixelStreamingInfrastructure-archived-2024#494]
**UE Version:**
E.g. UE 5.1.1+

**Frontend Version:**
UE5.1+

**Problem component**
Signalling Server WebRTC

**Description**
Sound capture via microphone doesn't work for MacBooks

**Steps to Reproduce:**
1. Build UE application that should record voice via Microphone.
2. Stream UE application via Pixelstreaming.
3. Open Stream on Macbook in Chrome or Safari.
4. Speak.
5. Check UE app what does it recieve(record) via browser.

**Expected behavior**
1. On Windows/Linux any browser can interact with UE via Pixelstreaming doing sound recordings.

**Screenshots**

**Platform (please complete the following information):**
 - OS: MacOS that comes with MacBook Intel, MacBook M1 and MacBook M2.
 - Browser Chrome 90+ and Safari

**Additional context**
In case of Chrome you can record sound with help of webrtc-internals and store it locally. Then yoou can play these files and listen that Chrome does recording properly. But sound from microphone isn't streamed to UE app.
If Pixelstreaming service taken from branch 5.0 this bug is not available and UE app can record sound from browser properly.

**Comment by DenisTensorWorks** [comment]
@vlobzakov 

The issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/19
It should be live shortly, so you can continue following the issue there. Thank you for your contribution!
