### ISSUE TITLE
[Enhancement] Hide the QPIndicator when the connexion quality is good and the control div when in fullscreen

### ISSUE THREAD

**Issue by TxMat** [EpicGames/PixelStreamingInfrastructure-archived-2024#496]
**Component your feature request relates to**
- [ ] Signalling server
- [ ] Frontend library
- [x] Frontend UI library
- [ ] Matchmaker
- [ ] SFU
- [ ] This repo

**Problem your feature solves? Please describe.**
While the default UI being very clean already, the persistant presence of the controls button and Video QP Indicator even in fullscreen causes a lot of clutter on the game view and can be distracting for players.

**Describe the solution you'd like**
It'll be nice to have options to tweak to behaviors of these components by hiding them in full screen or only show the connexion indicator when the quality is bad to alert the player.

**Additional context**
I've tried implementing these changes myself by [tinkering](https://github.com/TxMat/PixelStreamingInfrastructure/tree/UE5.3) with the library
 *disclaimer : i am not a typescript dev and my changes are probably a bit wonky*

**Comment by DenisTensorWorks** [comment]
@TxMat

The issue has been moved to the new repository: https://github.com/EpicGamesExt/PixelStreamingInfrastructure/issues/21
It should be live shortly, so you can continue following the issue there. Thank you for your contribution!
