### ISSUE TITLE
Adding Arm64 Support

### ISSUE THREAD

**Issue by circlenaut** [EpicGames/PixelStreamingInfrastructure-archived-2024#51]
Any interest in adding support for Arm64? Specifically Amazon's Graviton2/3 CPUs. If no one has started working on or unwilling to share, I wouldn't mind tackling this and submitting a PR.

**Comment by lukehb** [comment]
Do you mean the C++ Pixel Streaming plugin generally? Or specifically the servers and frontend contained in this repo, or both?

**Comment by lukehb** [comment]
To answer your question too, Arm64 is not on our roadmap right now. Though, we have considered the work that would be required for it as the requirement for ARM + PS does come up from time to time.

**Comment by lukehb** [comment]
Closing due to lack of reply from OP - but we are willing to accept such a PR.
