### ISSUE TITLE
Drops New streamer connections 

### ISSUE THREAD

**Issue by shashi0d** [EpicGames/PixelStreamingInfrastructure-archived-2024#52]
hello, current implementation drops multiple instances of games streaming 
13:51:24.318 Dropping new streamer connection, we already have a connected streamer
13:51:33.890 Dropping new streamer connection, we already have a connected streamer

with above message

I'm trying to implement a case where every player has his own unique experience for which we need as many game connections as players  ref:https://docs.unrealengine.com/5.1/en-US/hosting-and-networking-guide-for-pixel-streaming-in-unreal-engine/

Am I missing something here, or the method for that has changed?

please help me in this aspect

**Comment by Belchy06** [comment]
Hey there @shashi0d,

Unfortunately, the signalling server only supports a single streamer as evident in the log message you've posted.

On the web page you've linked, you'll notice that the image under the **Multiple Full Stacks with Matchmaking** shows a setup in which each streamer (application) also has its own respective signalling server with the Matchmaker being responsible for routing new players to a free instance.

I'd suggest trying to run a configuration similar to the one described above and letting us know how it goes.

Cheers
