### ISSUE TITLE
Sound is bad on 5.1

### ISSUE THREAD

**Issue by KungFuDonkey** [EpicGames/PixelStreamingInfrastructure-archived-2024#54]
After an upgrade from 5.0 to 5.1 the sound of unreal is really bad. We currently experience a bunch of 'hickups' and 'ticks' in the sound. This is not the case when we downgrade again to 5.0. I do not know where the issue comes from, only that this happens when we build in 5.1. 

We did notice that 'red' is used now for sound and that more additional parameters are used in the sound of the pixel stream. Disabling these from the unreal PixelStreaming Plugin and the signalling server side did not result in any improvement in the sound. 

Next to this the main issue that we face is that the recording of the microphone sounds really bad in the new version of the pixel stream. It sounds like the sample rate changed a little bit, even though the audio consumer still reports the sample rate to be 48khz. We cannot really use 5.1 now for our project because of this and we will revert to 5.0 for the time being, but we would like to move to 5.1 in the future.

I hope someone with more knowledge of webrtc can look into this and fix these issues such that 5.1 will work with normal sound.  

Edit:
Here are the specs of the PC so you can rule that out:
Laptop: Omen 16n-0690nd
CPU: Amd ryzen 6800H
GPU: Nvidia RTX 3060 laptop gpu
RAM: 32GB DDR 5

it runs our game at ~150 fps

**Comment by Belchy06** [comment]
Hey @KungFuDonkey,

We've recently pushed the fix for the poor mic input to all versions on the Pixel Streaming Infrastructure.

Give it a go and let us know how it goes!

Cheers

**Comment by KungFuDonkey** [comment]
yes I noticed the fix, however we now notice that the bitrate goes over the MaxBitrate setting. We think this might be an issue with the renegociation that happens in the new version, but we cannot say this for certain.

**Comment by Belchy06** [comment]
@KungFuDonkey Which bitrate? The audio or video bitrate?

**Comment by KungFuDonkey** [comment]
@Belchy06 From the top of my head it was the video bitrate that exceeded the MaxBitrate setting. I will close this issue for now and make a new issue next week in which I will have more details about this issue. For now thanks for fixing the audio :).
