### ISSUE TITLE
Mouse cursor doesn't work in some UE 5.1 projects

### ISSUE THREAD

**Issue by JRosenschon** [EpicGames/PixelStreamingInfrastructure-archived-2024#56]
I used Pixel Streaming with Unreal 4.27 and recently wanted to update my project to 5.1.
I updated my Unreal project and started your original SWS from the **UE5.1** branch. I both tested starting the Unreal app as a standalone game and later via the editor (as Standalone Game) with the parameters: **-AudioMixer -AllowPixelStreamingCommands -PixelStreamingIP=localhost -PixelStreamingPort=8888**.
But I had the problem that the streamed application wasn't able to detect the mouse movement and click inputs. Keyboard inputs worked fine. Same issue with LockedMouse and HoveringMouse mode.

I tried to reproduce this behavior in freshly created Unreal projects (FP- & TP- default templates from Unreal) but the mouse input worked fine there.

But I managed it to recreate the problem with the [Lyra Sample Game](https://docs.unrealengine.com/5.0/en-US/lyra-sample-game-in-unreal-engine/) template. I created two projects with this template. Once for UE 5 and a second one for UE 5.1. I started them with the corresponding SWS from your **UE5.0** and **UE5.1** branches. The 5.0 stream is working fine. But the 5.1 Lyra stream has the same problem. The running application doesn't receive any data from mouse movement and inputs.

There appears to be a problem according updated unreal projects and templates created before Unreal 5.1. 
I couldn't figure out, if there are any settings for this kind of projects that I need to configure. Maybe this is a general bug or you might be able to tell me what I need to do.

The only information I was able to gather during my research according to this problem is this [community post answer](https://forums.unrealengine.com/t/ue-5-1-anyone-out-there-successfully-pixel-streamed-from-ue-5-1/680196/2?u=qvempire)

I couldn't find any errors in log files.

**Comment by moefreelancer83** [comment]
Hi @JRosenschon , I also have a similar issue, I'm letting my app and signalling server run on an AWS instance. There I can run pixel streaming smoothly with no issue, but when connecting to the server remotely I can't have control over my mouse, after each click it simply jumps on the top left corner of screen.

I noticed that in the `registerLockedMouseEvents` function the `requestPointerLock` and some events the "webkit" is missing, so  for example I changed `playerElement.requestPointerLock = playerElement.requestPointerLock || playerElement.mozRequestPointerLock;` to `playerElement.requestPointerLock = playerElement.requestPointerLock || playerElement.mozRequestPointerLock || playerElement.webkitrequestPointerLock;` , and actually there are more of this missing "webkit" prefixes.

Sad point it doesn't work still for me, I thought this could be something not intentional anyways.

**Comment by vamman** [comment]
Is there any update on having this fixed for 5.1?

**Comment by JRosenschon** [comment]
I have not found a solution myself, nor have I received a response from the developers yet.

**Comment by Cipr0** [comment]
Hi, i've had the same problem and i've been testing a view thing, for me the problem was coming from the "Async Loading Screen" plugin, disabling it fix the issue. I've put a comment on the market place page, now waiting for a fix/response.

Hope it fix the problem for you to ;)

**Comment by lukehb** [comment]
@MWillWallT Are you able to repro this issue?

**Comment by wurrego** [comment]
I am also having the same issue. 

- My project is UE5.1.1, built on Linux (Ubuntu 20.04). 
- Tested locally and on AWS with the older pixel streaming cirrus webserver and the released docker image from pixelstreaminginfrastructure. 
- I do not have the Async Loading Screen Plugin downloaded or enabled.  
- The only Plugins i have enabled are Cesium for Unreal & PixelStreaming
- And no dice, no mouse cursor in the web broswer client.  
- If i run the packaged game locally, the mouse cursor does display in the game engine client.

Also looking for suggestions to resolve

**Comment by lukehb** [comment]
@wurrego We cannot reproduce this issue. Are you able to share a project with us that reproduces this issue?

**Comment by lukehb** [comment]
Also to confirm, @wurrego you are able to run the project locally and connect with a local web browser and see no mouse. That is to say, AWS is not required to reproduce this issue?

**Comment by wurrego** [comment]
> Also to confirm, @wurrego you are able to run the project locally and connect with a local web browser and see no mouse. That is to say, AWS is not required to reproduce this issue?

That is correct. I can run the project locally and connect with a local web browser and not see the mouse cursor. 

Let me see if I can share an example project tomorrow that is able to reproduce the issue.

**Comment by lukehb** [comment]
> Let me see if I can share an example project tomorrow that is able to reproduce the issue.

@wurrego That would be a great help. Much appreciated.

**Comment by wurrego** [comment]
@lukehb Ok I created a very simple project that reproduces the issue. 

https://github.com/wurrego/ue5-test-project/


On ubuntu 20.04 after git clone:

- $UNREAL_ENGINE_DIR/Engine/Build/BatchFiles/RunUBT.sh -projectfiles -vscode -project=$PWD/TestProject.uproject -game -engine
- ./package.sh
- ./run.sh

**Comment by jgiovino2** [comment]
I was also able to reproduce this issue with the UE 5.1.1 linux .zip release bundle from Unreal and the 5.1 branch in PixelStreaminghInfrastructure, using the following steps:
    . create new blank cpp project
    . add pixel streaming plugin and restart
    . add additional launch parameters under editor settings->level editor -> play -PixelStreamingIP=localhost -PixelStreaminPort=8888
    . add player controller blueprint with show mouse and mouse events selected
    . add game mode base blueprint using new mouse controller
    . set game mode override in the world settings using new game mode
    . git clone PixelStreamingInfrastructure
    . start pixel streamer
    . launch game from editor as: "Standalone Game"

Game application window will have the mouse present (where it was absent before adding the mouse controller)
Browser http://localhost:80 will have the pixel streaming game instance without a mouse visible.

I ran @lukehb's PixelStreamingDemoMinimal by compiling it with the same UE 5.1.1 release and the PixelStreamer provided in that same PixelStreamingDemoMinimal repo.
Using http://localhost:80/PixelDemoMinimal.html the mouse is visible.
Using the default player.html the mouse is not visible.
The PixelStreamingDemo player controller BP_OrbitController does NOT have "Show Mouse Cursor" set.

Does this mean the solution is in the  PixelDemo.js ??
        inputOptions.controlScheme = ControlSchemeType.HoveringMouse;
        inputOptions.fakeMouseWithTouches = true;

**Comment by Belchy06** [comment]
@jgiovino2 For your use case and what I understand, you'll want to be using the "Hovering Mouse" control scheme.

Activating this control scheme using that latest frontend is as simple as flipping the "Control Scheme" toggle in the settings panel. The reason your cursor disappears is because you're using the "Locked Mouse" control scheme which isn't effected by any options you set in blueprints.

**Comment by Belchy06** [comment]
@JRosenschon We've identified the issue you're reporting and are attempting to reproduce using 5.2.

If you're comfortable using source builds of the Unreal Engine, there's a workaround that's been posted to the forums [here](https://forums.unrealengine.com/t/workaround-for-fpixelstreamingmodule-startupmodule-setting-invalid-targetwidow-on-streamer/736507)

**Comment by Belchy06** [comment]
Fix will be in for 5.2!

**Comment by lukehb** [comment]
Fix was on UE side - https://github.com/EpicGames/UnrealEngine/commit/9f448608c4fdc43f45e14bab2884e2a888914ab8

**Comment by PengChaoJay** [comment]
127.0.0.1/?hoveringMouse=true

**Comment by ghost** [comment]
I just rolled back my RTX 3060 driver by one month....and it solved
