### ISSUE TITLE
Could not initialize connection

### ISSUE THREAD

**Issue by victorjourne** [EpicGames/PixelStreamingInfrastructure-archived-2024#58]
Thanks for having release this useful package!

I am trying to use it **locally** on my Ubuntu 22 - RTX 3070 laptop, so after configuring, packaging and running a project under **UE 5.0.3** with : 
`./MyProject2.sh -PixelStreamingURL=ws://localhost:8888  -RenderOffScreen` -> [log](https://github.com/EpicGames/PixelStreamingInfrastructure/files/10345659/game.log)
And launched the Signalling and Web Server container with : 
`docker run -p 80:80 -p 8888:8888  ghcr.io/epicgames/pixel-streaming-signalling-server:5.0.3` -> [log](https://github.com/EpicGames/PixelStreamingInfrastructure/files/10345654/signaling-container.log)

I got this **error** message : 
> LogPixelStreamingSS: Connecting to SS ws://localhost:8888
> LogPixelStreamingSS: Error: Failed to connect to SS: Could not initialize connection.

Does it sound familiar to you? 

Thanks a lot in advance!

**Comment by Belchy06** [comment]
Hi @victorjourne,

Try adding `--network host` into your docker run command.

Let us know how it goes!

Thanks,
Will

**Comment by victorjourne** [comment]
Thanks for your answer @Belchy06 ! 
Indeed, `--network host` option enables to bind directly the container to the Docker host’s network. ([ref](https://docs.docker.com/network/network-tutorial-host/)).
Unfortunately, It didn't change anything in may case.
Nevertheless, it made me realise that I had a **proxy** through the host's network !
`unset http_proxy && ./MyProject2.sh -PixelStreamingURL=ws://localhost:8888  -RenderOffScreen` made pixel streaming work!
Many thanks!
