### ISSUE TITLE
Game crashes with more than 2 connections when using PixelStreaming with SFU

### ISSUE THREAD

**Issue by ashishdasari148** [EpicGames/PixelStreamingInfrastructure-archived-2024#62]
With reference implementations of the Signalling server and the SFU, when trying to connect from the 3rd tab, the game crashes. This issue is not reproducible if ?preferSFU=false.

```
Signal 11 caught.
Malloc Size=262146 LargeMemoryPoolOffset=262162
CommonUnixCrashHandler: Signal=11
[2023.01.16-12.13.11:591][244]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to write memory at address 0x0000000000000003

[2023.01.16-12.13.11:591][244]LogCore: Assertion failed: RecvResult.ok() [File:.\../Plugins/Media/PixelStreaming/Source/PixelStreaming/Private/PixelStreamingDataChannel.cpp] [Line: 52]
Failed to create Data Channel. Msg=Data channel creation failed
```

**Comment by lukehb** [comment]
We are working on this one. CC @StomyPX if you end up with a fix in hand, make sure we share relevant details on this ticket too.

**Comment by lukehb** [comment]
This is fixed in https://github.com/EpicGames/PixelStreamingInfrastructure/commit/c82e13bad3cbfa586dd5b88edacc651770265638
