### ISSUE TITLE
Update page information to new front-end steps. Customising Player Pages

### ISSUE THREAD

**Issue by MWillWallT** [EpicGames/PixelStreamingInfrastructure-archived-2024#98]
The newly added pages under `EpicGames/PixelStreamingInfrastructure/Frontend/Docs`  all contain information relevant to the previous version of PS Infra/front end.

Update the page info and clear out any old information that no longer applies.
Add extra information that may be missing.
Delete the TO-DO from the top of all the pages.

**Comment by Belchy06** [comment]
This one's waiting on the refactor to extract the UI from the business logic. Once that's done I'll get onto the docs

**Comment by lukehb** [comment]
Was waiting on https://github.com/EpicGames/PixelStreamingInfrastructure/pull/110 - but that is now landed! 🥳
